#!/bin/bash

usage () {
    echo "$0 [path]"
    echo "  translates input from 0-byte line endings to normal"
    echo "  line endings, runs less on the result"
    exit 1
}

if [ $# -eq 0 ]; then
    tr0n | less
else
    for f in "$@"; do
	tr0n < "$f" | less
    done
fi

