#!/usr/bin/perl -w

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname ..

  adapted COPY from _cj-git-tkdiff, see there
";
exit (@_ ? 1 : 0);
}

usage unless @ARGV==7;

our ($file2,
     $file1,
     $sha1_1,
     $perms_X,
     $hmunknownwhyagainfile2,
     $sha1_2,
     $perms_Y
    )= @ARGV;

use Chj::xperlfunc;

xsystem "tkdiff", $file1,$file2;
# ^ instead of xexec, since git diff issues a warning if we don't exit true.
