#!/usr/bin/perl -w

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname ..

  adapted COPY from _cj-git-tkdiff, see there
";
exit (@_ ? 1 : 0);
}

usage unless @ARGV==7;

our ($file2,
     $file1,
     $sha1_1,
     $perms_X,
     $hmunknownwhyagainfile2,
     $sha1_2,
     $perms_Y
    )= @ARGV;

use Chj::xperlfunc;
use Chj::xtmpfile;
use Chj::xopen 'xopen_read';

sub filter_file {
    my ($file)=@_;
    if (-e $file) {
	my $in= xopen_read $file;
	my $out= xtmpfile;
	while (<$in>) {
	    s/mtime="\d{10}"/mtime="<REMOVED-BY-$myname>"/sg;
	    $out->xprint($_);
	}
	$in->xclose;
	$out->xclose;
	$out
    } else {
	xopen_read "/dev/null"
	  #hehe, need an object with a path method, incidentally that works nicely
    }
}

our @f= map { filter_file $_ } ($file1,$file2);

xsystem "diff","-u", map { $_->path } @f;
# ^ instead of xexec, since git diff issues a warning if we don't exit true.
