#!/bin/bash

YOUTUBEDOWN=${YOUTUBEDOWN-youtubedown}

degoogle --pass \
    | »» perl -we 'my($url)=@ARGV; print "URL: $url\n"; exec $ENV{YOUTUBEDOWN}, @ARGV' 2>&1 \
    | tee >(log-timestamp --pid >> ~/.down.log)
