#!/usr/bin/perl -w

use strict; use warnings FATAL => 'uninitialized';

use Chj::xperlfunc;

my @pid;

for (@ARGV) {
    if (my $pid= xfork) {
	push @pid, $pid
    } else {
	xexec "_e-gnu", $_
    }
}

for (@pid) {
    xxwaitpid $_
}
