#!/usr/bin/perl -w

use strict;

$0=~ /([^\/]+)$/s;
my $me= $1;
sub usage {
    die "$me  list of packages to upgrade
  Checks each package whether it is really installed, and if yes,
  apt-get install's it.
";
    exit 1;
}

usage unless @ARGV;

# get list of installed packages
my %packs= map { chomp; $_=>1 } `dpkglist -i`; # dpkglist is from me too
$|=1;
for (@ARGV) {
    if (/^-/) {
        usage
    } else {
        if ($packs{$_}) {
            print "$me: calling apt-get for '$_'...\n";
            system qw(apt-get install),$_;
        } else {
            print "$me: package '$_' is not installed.\n";
        }
        print "\n";
    }
}

