#!/usr/bin/perl -w

use strict;

$0=~ /([^\/]+)$/s;
my $me= $1;
sub usage {
    die "$me  list of packages to upgrade
  Checks each package whether it is really installed, and if yes,
  apt-get install's it.
";
    exit 1;
}

usage unless @ARGV;

# get list of installed packages
our %packs= map { chomp; $_=>1 } `dpkglist -i`;

$|=1;

our @packs= grep {
    if (/^-/) {
        usage
    } else {
	my $installed= $packs{$_};
	if (!$installed) {
	    print "$me: package '$_' is not installed.\n";
	}	
	$installed
    }
} @ARGV;

use Chj::xperlfunc;

if (@packs) {
    xxsystem "apt-get", "install", "--", @packs;
}

