#!/bin/bash

if test -n "$1" -a "$1" != "-h" -a "$1" != "--help"; then
    if test "$1" = "-Z"; then
	display -window root "$1"
    else
	convert -geometry 1024x768! "$1" - | display -window root -
	
    fi
else
    echo "$(basename "$0") [-Z] someimagefile" 
    echo "  Puts file onto X root window"
    echo "  It zooms to 1024*768 by default, -Z to turn off."
fi

