#!/usr/bin/perl -w

use strict;
use Fcntl;
use Time::HiRes 'usleep';

my $num=shift||1;

sysopen STDOUT,"/dev/tty0", O_WRONLY or die "Konnte /dev/tty0 nicht öffnen: $!";
$|=1;
for (1..$num) {
	print "\007";
	usleep 120000;
}

