#!/bin/sh

if ! grep '^ -- ' debian/changelog | head -1 | grep -q "`perl -w -MChj::userfullname -e 'print userfullname'`" ; then
    if [ "$1" = "-f" ]; then
	shift
    else
	echo "Vermisse die Angabe Deiner Wenigkeit im debian/changelog. (Bitte eintragen oder/und Option -f angeben zum forcieren.)" >&2
	exit 1
    fi
fi

exec nice dpkg-buildpackage -uc -us -b -r'fakeroot -u' "$@"
