#!/usr/bin/perl -w

# Sam Dez  6 05:42:03 MET 2003
(my $email='pflanze%gmx,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname file(s)

  Remove trailing \\r's and \\n's.
  (Note: not per line, only at the end of the file!
   Also: doesn't work on stdin or '-'.)

  (Christian Jaeger <$email>)
";
exit @_ ? 1 : 0;
}

my @args;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
#     } elsif (/^--?X(?:XXX(?:=(.*))?)?$/) {
#         if (defined $1) {
#             $XXX=$1
#         } else {
#             $XXX=$ARGV[++$i] or usage "missing argument for '$_' option";
#         }
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}
usage unless @args;

use Chj::xopen qw(xopen_read);
use Chj::xtmpfile;

for my $filepath (@args) {
    my $content= (xopen_read $filepath)->xcontent;
    #chomp $content;
    if ($content=~ s/[\r\n]+\z//s) {
	my $out= xtmpfile $filepath;
	$out->xprint($content);
	$out->xclose;
	$out->xreplace_or_withmode($filepath);
	print "did change file '$filepath'\n";
    }
}

