#!/bin/bash

# cj {Wed Jan 16 17:08:00 2008}
# wrapper to add i18n latin1 mode to the git config file

set -eu

usage () {
    echo "usage: $0 [-f]"
    echo "  Options:"
    echo "  -f  proceed even if .git exists: "
    echo "      change i18n.commitencoding, and create .gitignore if it"
    echo "      doesn't exist already."
    exit 1
}

opt_force=""
if [ $# = 1 ]; then
    if [ x-f = x"$1" ]; then
	opt_force=1
    else
	usage
    fi
else
    if [ $# -gt 1 ]; then
        usage
    fi
fi

if [ -e ".git" ]; then
    if [ -n "$opt_force" ]; then
	echo ".git already exists, but proceeding to change the config"
    else
	echo ".git already exists; can only work on local directory; aborting."
	echo "Give -f option if you want to change the config."
	exit 1
    fi
else
    git init "$@"
fi

if [ -d ".git" ]; then
    if ! locale| grep -q UTF-8; then
	git config i18n.commitencoding latin1
    fi
    if [ ! -f ".gitignore" ]; then
	cat >> .gitignore <<EOF
*~
.gitignore

*.o
*.o[1-9]
*.o[1-9][0-9]
.test*

EOF
    fi
else
    echo "missing .git dir; can only work on local directory, thus aborting before post setup step."
    exit 1
fi
