#!/bin/bash

set -eu

TMPDIR=cj-git-targz-import-tempdir

if [ $# -ne 1 ]; then
	echo "usage: $0 suffix"
	echo "  import all *\"\$suffix\" tar(gz/bz2) files in the current directory"
	echo "  into a git repo in a newly created subdir '$TMPDIR'"
	echo "  suffix should probably be .tar.gz or .tgz or .tar.bz2 (inluding"
	echo "  the leading dot)"
	echo " Adds g-l listing to the commit msg unless the NO_ADD_MTIMES env var"
	echo "  is set."
	echo " Set MOVE_OUT_OF_SUBDIR=1 if you want it to move stuff out of a "
	echo "  single toplevel subdir using mv * (will not move dot files)."
	echo " Set MOVE_OUT_OF_SUBDIR=2 if you want it to move stuff out of a "
	echo "  single toplevel subdir using mv *, and rm -rf the toplevel dir."
	exit 1
fi

SUFFIX="$1"

mkdir "$TMPDIR"
cd "$TMPDIR"
cj-git-init

ls -rt ../*"$SUFFIX" | while read f; do
    rm -rf *
    tar xf "$f"  # relies on tar finding out decompression scheme by itself
    if [ 1 = "${MOVE_OUT_OF_SUBDIR-}" ]; then
	dir=`ls -d *`
	mv -i "$dir"/* .
	rmdir "$dir"  # assumes there are not dot files
    elif [ 2 = "${MOVE_OUT_OF_SUBDIR-}" ]; then
	dir=`ls -d *`
	mv -i "$dir"/* .
	rm -rf "$dir"  # assumes dot files are unimportant
    fi
    file=$(basename "$f")
    filedate=$(
	cd ..
	l "$file" | perl -wne 'chomp; m/(200\d-\d+-\d+ \d+:\d+) / or die "no match: $_"; print $1 or die'
    )
    name=$(basename "$f" "$SUFFIX")
    echo "$name  ($filedate)" > .git/_cjmsg
    git add .
    if [ "" = "${NO_ADD_MTIMES-}" ]; then
        echo >> .git/_cjmsg
	g-l >> .git/_cjmsg
    fi
    #cat .git/_cjmsg

    git commit -a -m "$(cat .git/_cjmsg)"
done
