#!/bin/bash

set -eu

error () {
    # "$@" shows the same thing but .. should use something that quotes instead.
    # shellcheck disable=SC2145
    echo "$0: $@" >&2
    exit 1
}

usage () {
    echo "$0 frompath/ topath [file-with-paths-to-keep]"
    echo "  copy (with hardlinks) frompath/ to (nonexisting) topath,"
    echo "  then remove all paths from the history except for those "
    echo "  listed in file-with-paths-to-keep if given, or stdin otherwise."
    echo " (Note: does not parse options, i.e. treats '--' as argument.)"
    exit 1
}

if test $# -lt 2; then
    usage
fi
frompath="$1"
shift
topath="$1"
shift

keeps="`tempfile`"

filterkeeps () {
    filter-whitespace|filter-trimspace
}

if test $# -gt 0; then
    filterkeeps < "$1" > "$keeps"
    shift
else
    filterkeeps > "$keeps"
fi

if test -e "$topath"
then
    error "topath exists"
fi

mkdir "$topath"

cp -r -l -- "$frompath"/.git "$topath"/.git

cd "$topath"

git reset --hard

cj-git-filter-branch -f --remove-all-but-those-in "$keeps" --prefix

rm "$keeps"

