#!/usr/bin/perl -w

# Mon Sep 12 22:07:49 EDT 2011
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname path(s)

  Follow given path(s) in the current repo and following the history
  from HEAD and show all paths that the file(s) has(have) had
  previously.

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
#our $opt_dry;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   #"dry-run"=> \$opt_dry,
	   ) or exit 1;
usage unless @ARGV;

use Chj::Git::Follow;

print "$_\n" or die
  for Chj::Git::Follow->new_paths(@ARGV)->paths;

#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
