#!/usr/bin/perl -w

# Thu Aug 14 10:42:31 CEST 2008
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname

  Create new changelog entry in debian/changelog with the version
  taken from git describe.

  Options:
  -b  force (passed to debchange)

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
our $opt_b;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   "b"=> \$opt_b,
	   ) or exit 1;
usage if @ARGV;

use Chj::Git::Functions ':all';
use Chj::xperlfunc;

xexec("debchange",
      ($opt_b ? "-b" : ()),
      "--newversion",
      xgit_describe_debianstyle());


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
