#!/usr/bin/perl -w

# Sat Jun 14 21:16:00 CEST 2008
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

# our $options=
#   +{
#    
#    };

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname



  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   ) or exit 1;
usage unless @ARGV;

use Chj::IO::Command;

sub ls_files {
    my $in= Chj::IO::Command->new_sender ("git","ls-files","-z");
    my @files;
    local $/="\0";
    while (<$in>) {
	chomp;
	push @files,$_
    }
    \@files
}

#use Chj::ruse;
use Chj::Backtrace; use Chj::repl; repl;
