#!/bin/bash

set -eu

if [ $# -lt 2 ]; then
	echo "usage: $0 from-mail to-mail [ git-filter-branch-options ]";
	echo "  filters the current git branch changing author and "
	echo "  committer email addresses from \$from-mail to \$to-mail."
	echo "  NOTE: does *not* change the address in commit messages"
	echo "  like in signed-off lines!"
	exit 1
fi

frommail="$1"
tomail="$2"

shift
shift

quotestring () {
    perl -MChj::singlequote=singlequote_sh -we 'print singlequote_sh($ARGV[0]) or die $!' "$1"
}

git filter-branch --env-filter \
    '
    if [ "$GIT_COMMITTER_EMAIL" = '"$(quotestring "$frommail")"' ]; then
        GIT_COMMITTER_EMAIL='"$(quotestring "$tomail")"'
    fi
    if [ "$GIT_AUTHOR_EMAIL" = '"$(quotestring "$frommail")"' ]; then
        GIT_AUTHOR_EMAIL='"$(quotestring "$tomail")"'
	GIT_COMMITTER_EMAIL='"$(quotestring "$tomail")"'
    fi
    ' \
     "$@"
