#!/bin/bash

set -eu

usage () {
    echo "$0 hgworkingdir futuregitworkingdir"
    echo "  --ah, see also: git-hg"
    exit 1
}

if [ $# -ne 2 ]; then
    usage
fi

source="$(chase "$1")"
target="$2"

(
    set -eu
    set -x
    git init "$target"
    cd "$target"
    hg-fast-export -r "$source"
    #git reset --hard
) || (
    echo "failed: if hg-fast-export is missing, you need to:"
    echo "  apt install hg-fast-export"
    false
)
