#!/usr/bin/perl -w

# Fri Sep  4 16:08:14 EDT 2009
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname from to

  one time (hmm?) conversion between two repository formats
  (well could keep .bzr or whatever in 'to'? what about the git filter-branch --msgfilter thingie tho?)

  from and to are specs of this format:
     repotype:path

  e.g.  bzr:foo git:bar

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   ) or exit 1;
usage unless @ARGV==2;

{
    package CJ_TAILOR::spec;
    use Class::Array -fields=> -publica=> 'type', 'path';
    use Chj::xrealpath ();
    sub new_parse {
	my $class=shift;
	my ($str)=@_;
	my $s=$class->new;
	my ($Type,$Path)= split /:/,$str,2
	  or die "missing : in str: '$str'";
	$Type=~ /^\w+\z/ or die "invalid type '$Type'";
	$Path= Chj::xrealpath::xrealpath( $Path); # hmm doesn't need to exist, right. but that's already handled this way correctly, cool. except if path ends with a slash then it has to exist hmwell gr.  and  is it  always this way in my implementation?....--ACHno, it isn't  just happened to have a foo in cdt.
	@$s[Type,Path]= ($Type,$Path);
	$s
    }
    end Class::Array;
}

our ($from,$to)= map {
    CJ_TAILOR::spec->new_parse ($_)
} @ARGV;

# create config file:

use Chj::xtmpfile;
my $tmp= xtmpfile;

##well, this may be a bad idea if tailor changes it's config file format but then hell what hell of an interface would it provide really.
#I'm currently using (Debian lenny) :
#$ tailor --version
#0.9.35

# TODO what kind of quoting does this file format need  grr?
$tmp->xprint("[DEFAULT]
verbose = True

[project]
target = ".$to->type.":target
start-revision = INITIAL
root-directory = ".$to->path."
state-file = ".$to->path.".tailor.state
source = ".$from->type.":source
subdir = .

[".$from->type.":source]
repository = ".$from->path."

[".$to->type.":target]
repository = ".$to->type."
");
## I'm not sure what repository = foo is for, it seems to be ignored? or is it really expected to be the type  ??.
## putting tailor.state in file *besides* the target dir, ok?.
## (Hm could use something else than . for subdir. I see, I thought it was subdir inside a repo. krwl)
$tmp->xclose;

use Chj::xperlfunc ':all';

xxsystem "tailor", "--configfile", $tmp->path;
##OH NO THIS tool S.CKS doesn't exit with non zero code in case of errors like: "Common base for tailor exceptions: 'bar' is not a known VCS kind: No module named bar"

# (do we want to keep the config ? shouldn't be necessary. since I
# have my own control about the versions of my script, so I know the
# contents.)


# now, fix the commit messages: do this in a separate branch  ok ?.
print STDERR "\nGoing to fix the commit messages...\n\n";
##sh.t, subsequent tailor runs will assume it should look at the master branch?
##what about multiple branches anyway,hmmmmmm.
##wll just use a better commit msg converter ?.--todo actually filter-branch all branches.? how far back...?  wl.  todo improve performance in future.  but.  how will tailor handle this. convert back or what?  or, will I clone the git repo and filter the clone???.

##just do it badly on 'the master branch' for now:

my $scmcode= '(let* ((rl (lambda () (read-line (current-input-port) #\newline #t))) (first (rl))) (let lp () (let ((l (rl))) (if (eof-object? l) (begin (newline) (display first)) (begin (display l) (lp))))))';
use Chj::singlequote 'singlequote_sh';
my $filtercode= 'gsi -e '.singlequote_sh ($scmcode);

xxsystem "git","filter-branch","--msgfilter", $filtercode; #hm not even saying master branch. just the current one. what  ever.

#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;

__END__

