#!/usr/bin/env perl

my $copyright= <<'COPYRIGHT';
# Copyright 2023 by Christian Jaeger <ch@christianjaeger.ch>
# Published under the same terms as perl itself
COPYRIGHT

use strict;
use utf8;
use warnings;
use warnings FATAL => 'uninitialized';
use experimental 'signatures';

my ($email_full)= $copyright=~ / by ([^\n]*)/s;

my ($mydir, $myname);
BEGIN {
    $0=~ /(.*?)([^\/]+)\z/s or die "?";
    ($mydir, $myname)=($1,$2);
}

use Chj::xperlfunc ":all";
use Chj::IO::Command;
use Chj::singlequote qw(singlequote_sh_many);
#use Chj::ruse;
#use Chj::Backtrace; 
#use FP::Show; use FP::Repl; use FP::Repl::Trap; #

sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    xprintln "$myname [ directories ]";
    xprintln "  Cleans the given directories or \`.\` of *~ files";
    xprintln "  (moving them to the trash).";
    xprintln "  Options:
  -r     descent into subdirs, too
  --dry  show actions instead of running them

  ($email_full)";
    exit (@_ ? 1 : 0);
}

my $opt_dry = 0;
my $opt_r = 0;

sub lp() {
    if (@ARGV) {
        my $a = $ARGV[0];
        if ($a eq "--help" or $a eq "-h") {
            usage
        } elsif ($a eq "-r") {
            $opt_r = 1;
            shift @ARGV;
            lp();
        } elsif ($a eq "--dry") {
            $opt_dry = 1;
            shift @ARGV;
            lp();
        } elsif ($a eq "--") {
            shift @ARGV;
        }
    }
}

lp;


sub _xxsystem {
    if ($opt_dry) {
        xprintln "+ ", singlequote_sh_many(@_);
    } else {
        xxsystem_safe @_;
    }
}

sub clean_r($dir) {
    my $in = Chj::IO::Command->new_sender("find", $dir, "-name", "*~",
                                          "-a", "-print0");
    local $/ = "\0";
    my @paths = map { chomp; $_ } $in->xreadline;
    $in->xxfinish;
    _xxsystem "trash", "--", @paths;
}

if ($opt_r) {
    if (@ARGV) {
        for my $d (@ARGV) {
            clean_r $d
        }
    } else {
        clean_r "."
    }
} else {
    if (@ARGV) {
        for my $d (@ARGV) {
            _xxsystem "trash", "--", glob "$d/*~";
        }
    } else {
        _xxsystem "trash", "--", glob "*~";
    }
}
