#!/bin/bash

if [[ $# -gt 1 || $1 = "--help" || $1 = "-h" ]]; then
    {
	echo "`basename "$0"` [ directory ]"
	echo "  Cleans the given directory or . from *~ files. (moves to trash)"
    } >&2
    exit 1
fi

if [ "$1" ]; then
    exec trash -- "$1/"*~
else
    exec trash -- *~
fi

