#!/bin/sh

if [ $# -gt 1 -o "$1" == "--help" -o "$1" == "-h" ]; then
    {
	echo "`basename $0` [ directory ]"
	echo "  Cleans the given directory or . from *~ files. (moves to trash)"
    } >&2
    exit 1
fi

if [ "$1" ]; then
    exec trash "$1/"*~
else
    exec trash *~
fi

