#!/bin/bash

set -euo pipefail
IFS=

log () {
    if [ ! -e ~/log/ ]; then
        private mkdir ~/log/
    fi
    echo "`date`  $@" >> ~/log/concentrate.log
}


if [ -e /opt/chj/hosts-in/bin/concentrate ]; then

    exec /opt/chj/hosts-in/bin/concentrate "$@"

else

    usage () {
        echo "$0 [start|stop|off]"
        exit 1
    }

    start () {
        linkchooser /etc/hosts-concentrate
        log start
    }

    stop () {
        linkchooser /etc/hosts-distractive
        log stop
    }

    if [ $# -gt 1 ]; then
        usage
    fi

    case "${1-}" in
        "")
            start
            ;;
        start)
            start
            ;;
        on)
            start
            ;;
        stop)
            stop
            ;;
        off)
            stop
            ;;
        *)
            usage
            ;;
    esac

fi
