#!/bin/bash

set -eu

LOG=/var/log/cj-concentrate.log

usage () {
    echo "$0 start|stop"
    echo "  also see log file at $LOG"
    exit 1
}

log () {
    (
	umask 077
	echo "`date`  $1" >> "$LOG"
    )
}


if [ $# -ne 1 ]; then
    usage
fi

PATH=/opt/chj/ssh-config-gen/:"$PATH"

infile=/etc/hosts-in
outfile=/etc/hosts

mycpp () {
    (
	printenv -0 | perl -wn0e 'print "-D$_"' | xargs -0 -- cpp /dev/fd/10 "$@"
	# | tee /dev/fd/2
    ) 10<&0
}


if [ -f "$infile" -a -f "$outfile" ]; then

    case "$1" in
	start)
	filter_file "$infile" | mycpp -DMODE_CONCENTRATE=1 > "$outfile"
	log start
	;;
	stop)
	filter_file "$infile" | mycpp -DMODE_CONCENTRATE=0 > "$outfile"
	log stop
	;;
	*)
	usage
	;;
    esac
else
    echo "missing '$infile' or '$outfile'"
    exit 1
fi

