#!/bin/bash
set -euo pipefail
# enable job control consistently, not just when there is a tty:
set -m
IFS=

if [ $# -gt 0 ]; then
    inplace $(cmd perl -wne 's/ *$//; print or die $!') "$@"
else
    perl -wne 's/ *$//; print or die $!'
fi
