#!/bin/bash

if [ $# -ne 1 -o "$1" == "-h" -o "$1" == "--help" ]; then
	echo "usage: $0 remotemachine"
	echo "  uses ssh and date command to *push* the date of the"
	echo "  local machine to remotemachine."
	exit
fi

ssh root@"$1" 'date -s "'"`date`"'"'

