#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

usage () {
    echo "$0 logfile cmd [args]"
    echo "  run cmd with stdout and stderr piped through log-timestamp to logfile "
    echo " (and tee'd to a tempfile); if cmd fails (non-zero exit code), cat "
    echo " the saved stderr+stdout to stdout."
    exit 1
}

if [ $# -lt 2 ]; then
    usage
fi

logfile="$1"
shift

tmpf=`tempfile`

exitcode=0

if ! "$@" 2>&1 | tee "$tmpf" | log-timestamp >> "$logfile"; then
    exitcode=${PIPESTATUS[0]}
    cat "$tmpf"
fi

rm "$tmpf"

exit $exitcode
