#!/usr/bin/perl -w

# Fre Apr 21 20:11:52 MEST 2006
(my $email='christian%jaeger,mine,nu')=~ tr/%,/@./;

use strict;

use Chj::xperlfunc;

our $baseurl= 'https://www.security-database.com/detail.php?alert=';

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname cvecode(s)

  Show the page(s) at $baseurl . cvecode, the latter being something
  similiar to CVE-200X-XXXX

  (Christian Jaeger <$email>)
";
exit(@_ ? 1 : 0);
}

my @args;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
#     } elsif (/^--?X(?:XXX(?:=(.*))?)?$/) {
#         if (defined $1) {
#             $XXX=$1
#         } else {
#             $XXX=$ARGV[++$i] or usage "missing argument for '$_' option";
#         }
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}
usage unless @args;

use URI::Escape 'uri_escape';

my @urls= map {
    my $cvecode= $_;
    uc($cvecode)=~ /^CVE-(\d+)-\d+\z/
      or usage "'$cvecode' doesn't seem to match the usual format of cve codes";
    $baseurl . uri_escape($cvecode)
} @args;

use Chj::Browser;
Browser_exec @urls;
