#!/bin/bash

if [[ $# -ge 1 && $1 = --stop ]]; then
    shift
    LANG=C daemonize --stop time make "$@"
else
    mvnumber nohup.out
    ulimit -S -v unlimited
    LANG=C daemonize --nice=10 time make "$@"
fi
