#!/bin/bash

if [[ $# -ge 1 && $1 = --stop ]]; then
    shift
    LANG=C daemonize --stop bash -c 'time make "$@"' X "$@"
else
    mvnumber nohup.out
    ulimit -S -v unlimited
    LANG=C daemonize --nice=10 bash -c 'time make "$@"' X "$@"
fi
