#!/bin/bash

set -eu

if [ $# -ne 1 ]; then
     echo "usage: $0 packagename"
     exit 1
fi

package="$1"
# shellcheck disable=SC2001
# : See if you can use ${variable//search/replace} instead.
packagename=`echo "$package"|sed s/:.*//`

links-local /usr/share/doc/"$packagename"/
