#!/bin/bash

set -eu

if [[ $# -lt 1 || "$1" = "-h" || "$1" = "--help" ]]; then
     echo "usage: $0 packagename[s]"
     exit 1
fi

try () {
    path="$dir"/"$1"
    if [ -e "$path" ]; then
	zless "$path" || true # not sure || true is necessary
	return 0
    else
	triedfiles="$triedfiles $path"
	return 1
    fi
}

view () {
    local package="$1"
    local packagename
    # shellcheck disable=SC2001
    # : See if you can use ${variable//search/replace} instead.
    packagename=`echo "$package"|sed s/:.*//`
    local dir=/usr/share/doc/"$packagename"
    local triedfiles=""
    
    try changelog.Debian.gz || try changelog.gz || {
	echo "could not find either of these files:$triedfiles" >&2
	exit 1
    }
}

for p in "$@"; do
    view "$p"
done
