#!/bin/bash

set -euo pipefail
IFS=

cmd='find "$@" -iname "*.wav" -o -iname "*.webm" -o  -iname "*.ogv"  -o  -iname "*.mp4" -o  -iname "*.mp3" -o  -iname "*.ogg" -o -iname "*.ogx" -o -iname "*.mpga" -o -iname "*.gif" | filter-size +1MB |» mv-parents-to ~/Videos/'

usage () {
    echo "$0 dir(s)"
    echo
    echo "  Runs: $cmd"
    echo
    echo "  I.e. moves away all the video and audio files from"
    echo "  the given directory/directories and subdirectories."
    exit 1
}

if [ $# -eq 0 ]; then
    usage
fi

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

eval "$cmd"
