#!/bin/bash

# cj Fri,  4 Mar 2005 12:06:51 +0100

set -e
set -u

if ! [[ ${STRIPOPT+set} = set ]]; then
    STRIPOPT=""  # default is shell syntax
fi

if [ $# -eq 3 ]; then
    STRIPOPT="$1"; shift
fi

if [ $# -ne 2 ]; then
    echo "$0 [option] file1 file2"
    echo "  does tkdiff if DISPLAY is set, or diff -u otherwise, on the"
    echo "  contents piped through sort and filter-stripcomments"
    echo "  If 3 arguments are given, the *first* is considered to be an"
    echo "  option to filter-stripcomments."
    exit 1
fi

file1="$1"
file2="$2"

tmp1="$(tempfile --suffix "$(echo "$file1"|perl -wne 's/\s'\''//sg; s|/|--|sg; print')")"
tmp2="$(tempfile --suffix "$(echo "$file2"|perl -wne 's/\s'\''//sg; s|/|--|sg; print')")"

trap "rm -f '$tmp1' '$tmp2'" 0  # programexit

trans() {
    filter-stripcomments $STRIPOPT < "$1" | csort > "$2"
}

trans "$file1" "$tmp1"
trans "$file2" "$tmp2"

if [[ ${DISPLAY+set} = set ]]; then
    tkdiff "$tmp1" "$tmp2"
else
    diff -u "$tmp1" "$tmp2"
fi
