#!/usr/bin/perl -w

# Fri May  6 22:52:06 EDT 2011
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname dir

  Set mtime of dir, and, recursively, all its child directories to the
  latest mtime of all items contained in it.

  This is not what happens when creating then modifying files and
  directories in place, of course, but since there's no creation time
  (short of misusing atime maybe) we have to assume that
  mtime==creation time. (For directories, we could infer that creation
  time is the oldest contained mtime or creation time, but for now,
  don't do that.)

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
#our $opt_dry;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   #"dry-run"=> \$opt_dry,
	   ) or exit 1;
usage unless @ARGV;

#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
