#!/bin/bash

usage () {
	echo "$0 packagename"
	echo "  show which packages are depending on or recommending packagename."
	exit 1
}

if [ $# -ne 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
	usage
fi


#nodepends=--no-depends
nodepends=""

reqs=$(apt-cache rdepends "$1" --important --recommends $nodepends --no-pre-depends | sed '/^[^ ]/ d')

if [ -z "$reqs" ]; then
	echo "no packages recommend $1."
else
	dpkg -l $reqs 2> >(grep -v "No packages found matching" >&2 ) |egrep '^(i|.i)'
fi
