#!/usr/bin/perl -w

use strict;
use Chj::backtick qw/xbacktick xsystem/;

sub usage {
    print "usage: dpkgS commandname|file/path
";
    exit;
}

usage unless @ARGV;
for (@ARGV) {
    if (/^-/) {
	usage
    } else {
	local $/;
	if (! /\//) { # it could be a command
	    my $path= xbacktick("which",$_);
	    if ($? == 0) {
		chop $path;
		$_=$path
	    }
	}
	my $realpath= xbacktick("chase",$_);
	if ($? == 0) {
	    chop $realpath;
	    xsystem "dpkg", "-S", $realpath;
	} else {
	    # a message has already been printed by chase
	    exit 1
	}
    }
}

