#!/usr/bin/perl -w

use strict;

$0=~ /([^\/]+)$/s;
my $me= $1;
sub usage {
  die "$me  list of packages to upgrade
  Checks each package whether it is really installed, and if yes,
  apt-get install's it.
";
  exit;
}

usage unless @ARGV;

# get list of installed packages
my %packs= map { chomp; $_=>1 } `dpkglist -i`; # dpkglist is from me too
$|=1;
my (@packfiles,@packnames);
for (@ARGV) {
  if (/^-/) {
    usage
  } else {
    my ($packname)= /^([^_]+)/;
    if ($packs{$packname}) {
      push @packfiles,$_;
      push @packnames,$packname;
    } else {
      print "$me: package '$packname' is not installed.\n";
    }
    print "\n";
  }
}
if (@packfiles) {
  print "$me: installing ".(join ", ",@packnames)."...\n";
  system qw(dpkg -i),@packfiles;
}
