#!/usr/bin/perl -w

use strict;
use Chj::backtick qw/xbacktick/;
use Chj::xperlfunc;

sub usage {
    print "usage: dpkgS commandname|file/path
";
    exit;
}

usage unless @ARGV;

my $errors=0;

for my $command_or_path (@ARGV) {
    if ($command_or_path=~ /^-/) {
	usage
    } else {
	local $/;
	my $path= do {
	    if ($command_or_path=~ /\//) {
		$command_or_path
	    } else {
		# it could be a command
		my $path= xbacktick("which",$command_or_path);
		if ($? == 0) {
		    chop $path;
		    $path
		} else {
		    $command_or_path
		}
	    }
	};
	my $realpath= xbacktick("chase",$path);
	if ($? == 0) {
	    chop $realpath;
	    if (not 0== xsystem "dpkg", "-S", $realpath) {
		$errors++;
	    }
	} else {
	    # a message has already been printed by chase
	    exit 1
	}
    }
}

exit ($errors? 1 : 0);
