#!/usr/bin/perl -w

use strict;

my $what;

if (@ARGV) {
    if ($ARGV[0]=~ /^--?a(?:ll)?$/) {
        $what= "a";
    } elsif ($ARGV[0]=~ /^--?i(?:nstalled)?$/) {
        $what= "i";
    } elsif ($ARGV[0]=~ /^--?ia$/) {
        $what= "ia";
    }
    if (@ARGV>1 or not $what) {
        print "dpkglist [-a[ll] | -i[nstalled]]

List packages in /var/lib/dpkg/status. -a means all, -i only installed
packages. Per default, -i is assumed. -ia means include kinds of half-installed.
";
        exit(0);
    }
} else {
    $what= "i";
}

use Chj::Debian::DpkgAptList 'dpkglist';
use Chj::Chomp;

dpkglist +{Package=>1,
	   Status=>1,
	  },
  sub {
      my ($d)=@_;
      my $name= Chomp $$d{Package}[0][0];
      my $status= Chomp $$d{Status}[0][0];
      print $name."\n"
	if ($what eq 'a'
	    or $status=~ /\sinstalled/
	    or ($what eq 'ia' and ($status=~ /unpacked/
				   # which one is more important?
				   or
				   $status=~ /^install ok/)));
  };
