#!/usr/bin/perl -w

use strict;

$0=~ /([^\/]+)$/s;
my $me= $1;
sub usage {
  die "$me  list of packages to upgrade
  Checks each package whether it is already installed, and if yes,
  dpkg --install's it.
";
  exit;
}

usage unless @ARGV;

# get list of installed packages
my $packs= do {
    # since backticks don't check the return code:
    my $h={};
    use Chj::IO::Command;
    my $in= Chj::IO::Command->new_sender("dpkglist","-i");
    while (<$in>) {
	chomp;
	$$h{$_}=1
    }
    $in->xxfinish;#!
    $h
};

$|=1;
my (@packfiles,@packnames);
for (@ARGV) {
    if (/^-/) {
	usage
    } else {
	my ($packname)= /^([^_]+)/;
	if ($$packs{$packname}) {
	    push @packfiles,$_;
	    push @packnames,$packname;
	} else {
	    print "$me: package '$packname' is not installed.\n";
	}
    }
}
if (@packfiles) {
    print "$me: installing ".(join ", ",@packnames)."...\n";
    system qw(dpkg -i),@packfiles;
}
