#!/usr/bin/perl -w

my $trash;
if ($ENV{TRASHCAN}) {
	$trash= $ENV{TRASHCAN}
} elsif (-e $ENV{HOME}."/Desktop/Trash/") {
	$trash=$ENV{HOME}."/Desktop/Trash/";
} elsif (-e $ENV{HOME}."/Desktop/Mülleimer/") {
	$trash=$ENV{HOME}."/Desktop/Mülleimer/";
} elsif (-e $ENV{HOME}."/.Trash/") {
    $trash=$ENV{HOME}."/.Trash/";
} else {
	die "Konnte Deinen Trashcan nicht finden. ";
}

exec "/usr/bin/du", $trash;
