#!/bin/bash

set -euo pipefail
IFS=

HASH=$(perl -we 'print join("\0",@ARGV) or die $!' "$(pwd)" "$$" E "$@" | sha1sum | printfield 1)
# have to use separate logdir for every instance or there will be lock failures. Meh.
LOGDIR=~/log/E-"$HASH"
private mkdir -p "$LOGDIR"
exec daemonize --start --hash-input "$HASH" --multilog "$LOGDIR" emacs "$@"
