#!/bin/bash

set -euo pipefail
IFS=

elastfile () {
    local dir="$1"
    e "`lastfile --fullpath "$dir"`"
}

if [ $# = 0 ]; then
    elastfile .
else
    for d in "$@"; do
	elastfile "$d"
    done
fi

