#!/bin/sh

if ! which e 2>/dev/null; then
    # being started from Gnome panel or some such
    # set up PATH and other pieces of the environment:
    source ~/.bash_profile
fi

if [ "$1" ]; then
    e "$@" &   # '--' schon von wmaker übergeben
else
    unset DIR
    DIR="$HOME/scratch"
    
    if [ ! -e "$DIR" ]; then
	umask 077;
	mkdir -p "$DIR"
    fi

    start () {
	e -- "$DIR/`date|tr ' ' '_'|sed 's/://g'`"
    }
    
    if tty >/dev/null; then
	# stay on foreground
	start
    else
	start &
    fi
fi
