#!/bin/bash

set -euo pipefail
IFS=

usage () {
    {
	echo "usage: $0"
	echo "  show email address including full name"
    } >&2
    exit 1
}

if [ $# -ne 0 ]; then
    usage
fi

echo "$(cat ~/.chj-home_fullname) <$EMAIL>"
