#!/bin/bash

set -euo pipefail
IFS=

usage () {
    {
	echo "usage: $0"
	echo "  show email address including full name"
    } >&2
    exit 1
}

opt_copy=0
if [ $# -gt 0 ]; then
    if [ "$1" = "-c" ]; then
        opt_copy=1
        shift
    else
        usage
    fi
fi

if [ $# -ne 0 ]; then
    usage
fi

fullname=$(cat ~/.chj-home_fullname)

if [ "${EMAIL_FULL_CLEAN-0}" = 1 ]; then
    fullname=$(printf '%s' "$fullname" | perl -wne 's/\s*\([^()]*\)\s*/ /s; s/\s+\z//; print')
fi

printit() {
    echo "$fullname <$EMAIL>"
}

if [ $opt_copy = 1 ]; then
    printit | xsel -i
else
    printit
fi

