#!/bin/bash

if [[ $# -ne 1 || $1 = "--help" || $1 = "-h" ]]; then
	echo "usage: $0 where"
	echo "  where 'where' is anything that whereami accepts."
	exit
fi
	

where="$1"

ifdown eth0
whereami -s "$where"
ifup eth0

