#!/bin/bash

set -eu

if [ $# -lt 2 ]; then
    findf-grep . "$@"
elif [ $# -ge 2 ]; then
    if [ -d "$1" ]; then
        findf-grep "$@"
    else
        findf-grep . "$@"
    fi    
else
    echo "usage: $0 [dir] regex [options]"
    exit 1
fi
