#!/bin/bash

set -eu

if [ $# -lt 2 ]; then
    find-f-grep . "$@"
elif [ $# -ge 2 ]; then
    if [ -d "$1" ]; then
        find-f-grep "$@"
    else
        find-f-grep . "$@"
    fi    
else
    echo "usage: $0 [dir] regex [options]"
    exit 1
fi
