#!/usr/bin/perl -w

# Mit Jun 30 01:32:18 MEST 2004
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname [infile(s)]
  strips whitespace from beginning and end of each line from infiles/stdin
  and adds a \\n to the last line of files if not already given.
  Output is always to stdout.
  (Christian Jaeger <$email>)
";
exit @_ ? 1 : 0;
}

my @args;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
#     } elsif (/^--?X(?:XXX(?:=(.*))?)?$/) {
#         if (defined $1) {
#             $XXX=$1
#         } else {
#             $XXX=$ARGV[++$i] or usage "missing argument for '$_' option";
#         }
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}

use Chj::xopen 'xopen_read';

sub slurp {
    my ($fh)=@_;
    while (<$fh>) {
	s/^\s+//s;
	s/\s+\z//s;
	print $_,"\n";
    }
}


if (@args) {
    for (@args) {
	my $f=xopen_read $_;
	slurp $f;
    }
}
else {
    slurp *STDIN{IO};
}


