#!/bin/sh

usage() {
    echo "Usage: $0 dir regex"
    echo "  Find all files (type f) in \$dir excluding backups files,"
    echo "  and run egrep \$regex to them."
    exit
    # ohoh, -a für all? und solche spässe, müsst ich wieder zu perl greifen
}

if [ $# -lt 2 ]; then
    usage
fi

dir="$1"
shift

if perl -we 'exit((grep{ if($_ eq "--"){goto notfound}; $_ eq "--fixed-strings" or /^-[^-]/ && /F/ && goto found } @ARGV) ? do{ found: 0 } : do{ notfound: 1})' -- "$@"; then
    #echo 'found -F flag'
    grep=grep
else
    grep=egrep
fi

find "$dir" -type f -a \! -name "*~" -a -print0 |xargs -0 $grep "$@"


#good:
#> find-f-grep .  Foo -- -F
#grep: -F: No such file or directory
#> find-f-grep .  Foo -F
#found -F flag
