#!/bin/bash

# cj Tue, 07 Mar 2006 13:59:10 +0100

set -eu

if [[ $# -lt 2 || $1 = "-h" || $1 = "--help" ]]; then
    echo "usage: $0 dir pattern"
    exit
fi

dir="$1"
shift
find "$dir" -name "*pm" -print0 | xargs -0 grep "$@"

