#!/bin/sh

# Copyright (c) 2015-2019 Christian Jaeger, copying@christianjaeger.ch
# This is free software. See the file COPYING.md that came bundled
# with this file.

# load repl with most of the more interesting functional-perl packages
# loaded

repl=/opt/functional-perl/bin/repl

exec $repl \
    --name fperl \
    -t \
    -m Method::Signatures \
    -m Function::Parameters=:strict \
    -m Sub::Call::Tail \
    -M FunctionalPerl=:all \
    "$@"
