#!/bin/bash
set -meuo pipefail
IFS=

usage() {
    echo "Usage: $0 commitrange1 commitrange2"
    echo "Usage: $0 base commit1 commit2"
    echo
    echo "  Compare the commits from two commit ranges, as git patch files "
    echo "  compared via 'diff'. If 3 arguments are given, constructs the ranges "
    echo "  as 'base..commit1' and 'base..commit2'."
    echo
    echo "  Currently only works well if the commit counts and oder are the same,"
    echo "  as otherwise the patch files will have different names."
    exit 1
}

if [ $# -eq 2 ]; then
    range1=$1
    range2=$2
elif [ $# -eq 3 ]; then
    range1="$1..$2"
    range2="$1..$3"
else
    usage
fi

dir=$(mktemp -d)

mkdir "$dir"/{A,B}

trap 'rm -rf -- "$dir"' EXIT

# set -x

git format-patch --quiet -o "$dir/A" "$range1"
git format-patch --quiet -o "$dir/B" "$range2"

diff -rubBN "$dir/A" "$dir/B" | less -p '^[-+][^-+].*'
