#!/usr/bin/perl -w

# Sat Aug  9 13:43:20 CEST 2008
(my $email='ch%christianjaeger,ch')=~ tr/%,/@./;

use strict;

# I don't like shell auto completion (it costs memory, and I don't
# like the unpredictability).  Could add /usr/lib/git-core/ to PATH,
# but using g-* symlinks there's less to type.  Using g-* and not just
# g* to avoid some conflicts.

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);

my $start= "g-";

$myname=~ /^$start(.*)/
  or die "we were called as '$myname', which is not starting with '$start'";

exec "git", $1, @ARGV
  or die "could not exec 'git': $!";
