#!/bin/bash
set -meuo pipefail
IFS=

for arg in "$@"; do
    if [ "$arg" = "--hard" ]; then
        git cherry-pick --abort >/dev/null 2>&1 || true
        git rebase --abort >/dev/null 2>&1 || true
        git merge --abort >/dev/null 2>&1 || true
        exec git reset "$@"
    fi
done

exec git reset "$@"
