#!/bin/bash

ulimit -S -v 300000 # statt 110000

#exec gdb /usr/local/Gambit-C/bin/gsc -- -:tE,d-,t8,f8,tn -i -e '(include "~/.gam.scm")' -
# geht alles partuou nicht grrrr

PATH="$HOME/bin-gam-emacs-gdb:$PATH"

exec gdb -x ~/bin/gam-emacs-gdb.command /usr/local/Gambit-C/bin/gsc

