#!/bin/sh

paths='
 /usr/local/Gambit-C/current/doc/gambit-c.html
 /home/rchris/install/gambc/doc/gambit-c.html
'

for path in $paths; do
    if [ -e "$path" ]; then
	exec links "$path" "$@"
    fi
done

echo "finde gambit manual nicht, sollte irgendwo sein wie bei $paths"
exit 1
