#!/bin/sh

paths="
 /usr/local/Gambit-C/current/doc/gambit-c.html
 /usr/local/Gambit-C/doc/gambit-c.html
 $HOME/install/gambc/doc/gambit-c.html
 $HOME/local/doc/gambit-c.html
 /home/rchris/install/gambc/doc/gambit-c.html
"

for path in $paths; do
    if [ -e "$path" ]; then
	exec links "$path" "$@"
    fi
done

echo "can't find manual, should be somewhere like: $paths"
exit 1
