#!/usr/bin/perl -w

# Mon Mar 22 14:41:52 EDT 2010
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname tagsubname [reset_to_commit]

  Options:
  -f   force it even if the working directory is not clean
  -a   passed to git tag
  -s   passed to git tag

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
#our $opt_dry;
our $opt_force;
our @gitopts; our $addgitopt= sub {
    my (@opts)=@_;
    sub {
	#push @gitopts, $_[0];
	push @gitopts, @opts
    }
};
#^hh currying with  sideeffect y y knw
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   #"dry-run"=> \$opt_dry,
	   "a"=> &$addgitopt("-a"),
	   "s"=> &$addgitopt("-s"),
	   "force"=> \$opt_force,
	   ) or exit 1;
usage unless (@ARGV>=1 and @ARGV<=2);

our ($maybe_subname, $maybe_reset_to_commit)=@ARGV;

our $subname_= ((defined ($maybe_subname))# and length ($maybe_subname))
		? $maybe_subname."_" : "");

our $date_= `date_`; chomp $date_; #hum.
our $tagname= "drop_".$subname_.$date_;

use Chj::xperlfunc;

use Chj::IO::Command;

sub status_is_clean {
    my $in= Chj::IO::Command->new_combinedsender( "git","status");
    my $incnt= $in->xcontent;
    my $instatus= $in->xfinish;
    [
     (scalar ((($instatus==(1<<8)) or ($instatus==0))
	      and
	      $incnt=~ /\nnothing to commit .working directory clean/)),
     $incnt
    ]
}

our $cleanq= do {
    my $res;
    sub {
	$res ||= status_is_clean;
	$res
    }
};

if ($opt_force or (&$cleanq)->[0]) {
    xxsystem "git", "tag", @gitopts, $tagname;
    if (defined $maybe_reset_to_commit) {
	xxsystem "git", "reset", "--hard", $maybe_reset_to_commit;
    }
} else {
    print STDERR "\n  *** working directory status is not clean: ***\n\n"
      .(&$cleanq)->[1];
    exit 1;#well, die, but?,.
}


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
