#!/usr/bin/perl -w

# Mon Mar 22 14:41:52 EDT 2010
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname tagsubname [reset_to_commit]

  Options:
  -a   passed to git tag
  -s   passed to git tag

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
#our $opt_dry;
our @gitopts; our $addgitopt= sub {
    my (@opts)=@_;
    sub {
	#push @gitopts, $_[0];
	push @gitopts, @opts
    }
};
#^hh currying with  sideeffect y y knw
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   #"dry-run"=> \$opt_dry,
	   "a"=> &$addgitopt("-a"),
	   "s"=> &$addgitopt("-s"),
	   ) or exit 1;
usage unless (@ARGV>=1 and @ARGV<=2);

our ($maybe_subname, $maybe_reset_to_commit)=@ARGV;

our $subname_= ((defined ($maybe_subname))# and length ($maybe_subname))
		? $maybe_subname."_" : "");

our $date_= `date_`; chomp $date_; #hum.
our $tagname= "drop_".$subname_.$date_;

use Chj::xperlfunc;

use Chj::IO::Command;
our $in= Chj::IO::Command->new_combinedsender( "git","status");
our $incnt= $in->xcontent;
our $instatus= $in->xfinish;

#if ($instatus==0) {
#ehr wrong. sigh.
if ($instatus==(1<<8) and
    $incnt=~ /\nnothing to commit .working directory clean/) {
    xxsystem "git", "tag", @gitopts, $tagname;
    if (defined $maybe_reset_to_commit) {
	xxsystem "git", "reset", "--hard", $maybe_reset_to_commit;
    }
} else {
    print STDERR "** work directory status is not clean:\n\n$incnt";
    exit 1;#well, die, but?,.
}


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
