#!/bin/bash
set -euo pipefail
IFS=

usage() {
    echo "Usage: $0 [file-grep-options] regex [lst-options]"
    echo "  The file-grep-options string is passed to lst's file-grep filter command."
    echo "  If only regex is given, the defaults are used."
    echo "  lst-options are '-'-based options for lst."
    exit 1
}

lst_options=()

if [ $# = 0 ]; then
    usage
elif [ $# = 1 ]; then
    #if [ "$1" = -h ] || [ "$1" = --help ]; then
    #    usage
    #fi
    options=""
    regex="$1"
    
else
    options="$1"
    regex="$2"
    shift
    shift
    lst_options=("$@")
fi

git ls-files -z | lst -z "${lst_options[@]}" -- filter f file-grep "$options" "$regex"
