#!/bin/bash
set -meuo pipefail
IFS=

usage() {
    echo "$0 commitid etc."
    echo "  Runs git reset --keep and your arguments"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi
if [ "$1" = -h -o "$1" = --help ]; then
    usage
fi

git reset --keep "$@"
