#!/usr/bin/perl -w

# Sun Aug 16 11:32:55 EDT 2009
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname [further arguments and/or files]

  run git log --raw, additionally with --follow if exactly 1 file has
  been given.

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

if (@ARGV==1 and ($ARGV[0] eq "-h" or $ARGV[0] eq "--help")) {
    usage
}

sub lg {
    exec "git","log","--raw",@_,@ARGV
      or die $!
}

if ((@ARGV==2 and $ARGV[0] eq "--") or (@ARGV==1 and not $ARGV[0]=~ /-/)) {
    lg("--follow")
} else {
    lg()
}


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
