#!/usr/bin/perl -w

# Sun Aug 16 11:32:55 EDT 2009
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname [further arguments and/or files]

  run git log --raw -M -C, additionally with --follow if exactly 1
  file has been given.

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

if (@ARGV==1 and ($ARGV[0] eq "-h" or $ARGV[0] eq "--help")) {
    usage
}

sub lg {
    exec "git","log","--raw","-M","-C",@_,@ARGV
      or die $!
}

my $number_of_files = do {
    my $i=0;
    my @args= @ARGV;
    while (@args) {
	my $a=shift @args;
	if ($a eq "--") {
	    warn "hm i=$i";
	    $i+= @args;
	    last;
	}
	if ($a =~ /-/) {
	    # ignore.
	    # well but are there flags with a followup argument ?
	    # doesn't seem so. except maybe: '-O<orderfile>' could be valid with a space afer O ? nope.
	    # what about the = stuff like '--dst-prefix=<prefix>'?: nope, space instead of = is not valid.
	    # cool finally a program that does it sensibly rit.
	} else {
	    #hm. is it a revision not a file ? :
	    if (-e $a) {
		warn "a file: '$a'";
		$i++
	    } else {
		die "does not exist: '$a' : $!\n";
		# ignore
	    }
	}
    }
    warn "i=$i";
    $i
};

#print "number_of_files=$number_of_files\n\n";

if ($number_of_files==1) {
    lg("--follow")
} else {
    lg()
}


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
