#!/bin/bash

# ls-files without -z encodes filenames with special characters into a
# quoted form; avoid this (even if it means newlines are going to be
# unsafe; for a safe listing, use gls0)

set -euo pipefail
git ls-files -z "$@" | tr '\0' '\n'
