#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "usage: $0 suffix-without-dot-regex [gls-arguments]"
    echo "  \`git ls-files\` filtered by the files with end in the given suffix."
    exit 1
}


if [ $# -lt 1 ]; then
    usage
fi

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

export SUFFIX="$1"
shift

git ls-files -z "$@" | perl -wn0e 'chomp; print "$_\n" or die "stdout: $!" if /\.(?:$ENV{SUFFIX})\z/o'

