#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "usage: $0 [gls-options]"
    echo "  \`git ls-files\` distilled down to suffix statistics"
    exit 1
}


if [ $# -gt 0 ]; then
    if [ "$1" = "-h" -o "$1" = "--help" ]; then
        usage
    fi
fi

git ls-files -z "$@"| perl -wn0e '
chomp;
if (m{([^/]+)\.([^.\s\)\"\!\?]+)$}) {
    $suffix{$2}++
       unless $1 eq "my";
}
END {
    for (sort { $suffix{$a} <=> $suffix{$b} or $a cmp $b } keys %suffix) {
        print "$suffix{$_}\t$_\n" or die "stdout: $!"
    }
}
'

