#!/bin/bash

set -eu

usage () {
    echo "$0 [commitid(s)]"
    echo "  print patchid for each commitid (reads from stdin if none given)"
    echo "  (Note: also see Chj/Git/Patchid.pm)"
    exit 1
}

gpatchid() {
    id="$1"
    git diff-tree -p -M50 -C60 "$id" | git patch-id
}

if [ $# -eq 0 ]; then
    while IFS='' read id; do
	gpatchid "$id"
    done
else
    if [ "$1" = "-h" -o "$1" = "--help" ]; then
	usage
    else
	for id in "$@"; do
	    gpatchid "$id"
	done
    fi
fi

