#!/bin/bash

set -eu

usage () {
    echo "usage: $0 base onto"
    echo "  move commits \$base..HEAD onto \$onto"
    echo "  and check out \$onto (well that's being done first actually)"
    exit 1
}

if [ $# -ne 2 ]; then
	usage
fi

base="$1"
onto="$2"

git checkout "$onto"
git rebase --onto "$2" "$1"
