#!/bin/bash

set -eu

usage () {
    echo "usage: $0 base onto"
    echo "  move commits \$base..HEAD onto \$onto"
    echo "  which is just: git rebase --onto \$onto \$base"
    echo "  but I tend to always forget."
    exit 1
}

if [ $# -ne 2 ]; then
	usage
fi

exec git rebase --onto "$2" "$1"
