#!/usr/bin/perl -w

# Mon Okt 31 16:31:30 MET 2005
(my $email='pflanze%gmx,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname [options] regex files

 Options:
  -F   not a regex but fix text
#  -c   create dir  well no that's the default anyway.
  -d  dirbase   base path where the dir schould be creaated where the files should be moved to.

  (Christian Jaeger <$email>)
";
exit(@_ ? 1 : 0);
}

my @args;
my $DEBUG=0;
my ($opt_F,$opt_dirbase);
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?F$/) {
	$opt_F=1;
    } elsif (/^--?d(?:irbase)?(?:=(.*))?$/) {
        if (defined $1) {
            $opt_dirbase=$1
        } else {
            $opt_dirbase=$ARGV[++$i] or usage "missing argument for '$_' option";
        }
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}
usage unless @args;

usage "missing -d option" unless $opt_dirbase;#?
my $dirbase= defined($opt_dirbase) ? $opt_dirbase : ".";

my $pattern=shift @args;

use Chj::xperlfunc qw(xlinkunlink xmkdir);
use Chj::Web::FileescapeUrl qw(fileescapeurl);
use Chj::xopen 'xopen_read';
use Chj::singlequote;

my $dirname= "." . ($opt_F ? "F" : "R") . fileescapeurl $pattern;
my $dirpath= "$dirbase/$dirname";
unless (-d $dirpath) {
    xmkdir $dirpath;
    print "created directory ".singlequote($dirpath)."\n";
}



my $regex= do {
    if ($opt_F) {
	qr/\Q$pattern\E/s
    } else {
	qr/$pattern/s
    }
};

sub matchfile {
    my ($filepath)=@_;
    my $cntrf= \ (xopen_read($filepath)->xcontent);
    $$cntrf=~ /$regex/
}

my $moved=0;
sub movefile {
    my ($filepath)=@_;
    my $filename= $filepath;
    $filename=~ s|.*/||s;
    xlinkunlink $filepath,"$dirpath/$filename";# ??? warum gibt es Useless use of string in void context at /root/bin/grepmvnewdir line 94.   wenn ich keine klammern setze hier ? weil eben als methode verstanden ?. aha ja.
    $moved++;
}

for my $filepath (@args) {
    movefile($filepath)
      if matchfile($filepath);
}

print "moved $moved files (out of ".@args.").\n";
