#!/bin/bash

set -eu

usage () {
    echo "$0 tagname"
    echo "  runs gdrop --no-prefix <tagname>"
    ## hmm, pass through -a option though ?
    ## as well as -s ?
    ## should really change gdrop instead
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi
if [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

exec gdrop --no-prefix "$@"
