#!/bin/bash

set -eu

default_outpath=../$(basename "$(pwd)").tar.xz

help () {
    echo "$0 [id outpath]"
    echo "  outpath should end in .tar, .tgz, .tar.gz, .tar.bz2, .tar.xz"
    echo "  If no argument is given, uses: HEAD $default_outpath"
    exit 1
}

if [ $# -eq 2 ]; then
    id="$1"
    outpath="$2"
elif [ $# -eq 0 ]; then
    id=HEAD
    outpath=$default_outpath
else
    help
fi


base=`echo "$outpath"| perl -wne 'chomp; s{\.(tar|tgz)[^/]*$}{}s; print'`

produce () {
    local bn
    bn=`basename "$base"`
    git archive --format=tar --prefix="$bn"/ "$id"
    # ^yeah, don't forget the / ..
}

if echo "$outpath" | grep -q 'gz$'; then
    produce | gzip > "$outpath"
elif echo "$outpath" | egrep -q '\.xz$'; then
    produce > "$base.tar"
    xz "$base.tar"
elif echo "$outpath" | egrep -q '\.rz$'; then
    produce > "$base.tar"
    rzip "$base.tar"
elif echo "$outpath" | egrep -q 'bz2$'; then
    produce > "$base.tar"
    bzip2 "$base.tar"
else
    produce > "$outpath"
fi
