#!/usr/bin/perl -w

# Thu Feb 26 12:23:21 EST 2009
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname ..

  Wrapper around 'halt' so that I don't erroneously shut down a machine.
  (especially my fine laptop with the broken new setup that doesn't go
  to sleep w/o crashing)

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   ) or exit 1;
#usage unless @ARGV;

use Chj::Util::AskYN;

our @orig_halt= "/sbin/halt";
#our @orig_halt= "echo";

use Chj::xperlfunc;

if (maybe_askyn "Are you sure you want to run 'halt'?") {
    xexec (@orig_halt, @ARGV);
} else {
    die "cancelled by user\n";
}


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
