#!/bin/bash

set -euo pipefail
IFS=

usage() {
    echo "$0 file"
    echo "  print the first line, and then tail -f the rest"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

head -1 "$1"
echo ...
fasttail "$1"
