#!/bin/bash
echo "
Kleine Übersicht von Befehlen auf diesem Rechner:
----------------------------------------------------------------
w           wer ist eingeloggt?
who         +- dasselbe
talk Name   Text-chat mit 'Name' starten (Name von 'w' ersichtlich)
ls          Zeige Inhalt des aktuellen Verzeichnisses
l           sortiertes Listing, absteigend nach Datum sortiert, 
            farbig hervorgehoben
cd Ordner   change directory: wechsle Standort in 'Ordner' hinein 
            (kann auch ein ganzer '/Pfad/nach/irgendwo' sein)
cd ..       aus dem aktuellen Ordner herausgehen
pwd         Aktueller Standort (\"print working directory\")
less Datei  Zeigt Inhalt der 'Datei' an. Scrollen ist möglich (PageUp/
            Down oder 'w'/Space);  Textsuche durch Eingabe von '/' 
            und suchtext.
            Mit 'q' wird less wieder verlassen.
mv quelle ziel    
            Datei verschieben oder umbenennen
rm datei    Datei löschen
man Befehl  manual: zeigt Hilfestellung zu 'Befehl' an. Bedienung
            analog zu 'less'
apropos Stichwort  
            Listet alle Befehle auf, zu welchen in den Manuals
            von 'Stichwort' die Rede ist.
mail        Simples Mailprogramm, um die Systemmails (Meldungen etc)
            anzusehen. Mit '?' kriegt man eine Liste der Befehle.
            (Mit der Eingabetaste kann man die Mails durchblättern,
            mit q verlässt man das Programm.)
passwd      Passwort ändern (frägt interaktiv ab)


Tips:
----
* Mit Control-C lassen sich die meisten Programme abbrechen.
* Mit der Tabulatortaste lassen sich angefangene Befehle, Pfadangaben 
  etc. automatisch vervollständigen. Zweimaliges drücken von Tab zeigt 
  eine Liste der möglichen Vervollständigungen, falls es mehrere gibt.
* Mit den Pfeil-nach-oben/unten-Tasten können alte Eingabezeilen 
  zurückgeholt werden. (Mit Ctrl-r und tippen von Buchstaben
  wird die letzte Zeile mit diesen Buchstaben gesucht; weitere Ctrl-r
  zum weiter zurückgehen.)
* Bewegen in der Eingabezeile ist möglich mit home/end-Tasten, Cmd-f/b 
  (word forward/back) und anderen;  Ctrl-/ ist Undo.
* Die meisten Befehle zeigen eine kurze Hilfestellung an, wenn man sie
  mit '-h' oder '--help' als Argument aufruft (z.B. 'mv --help')

Verlassen dieser Seite mit 'q'.
cj."|less
