#!/bin/bash

set -euo pipefail
IFS=

if [ $# -ge 1 ]; then
    for f in "$@"; do
        htmlparse --links -- "$f"
    done
else
    echo "usage: $0 file"
    echo "  run htmlparse --links and the given file"
    exit 1
fi

