#!/bin/bash

if [[ $# -gt 1 || $1 = "-h" || $1 = "--help" ]]; then
	echo "usage: $0 [ interface ]"
	echo "  down and up the interface or eth0 if none given"
	exit 1
fi

iface="${1:-eth0}"

ifdown --force "$iface"
ifup "$iface"
