#!/bin/bash
set -euo pipefail
IFS=

usage() {
    echo "Usage: $0 [options] name-regex"
    echo "  Search for 'impl' of the trait or type named name-regex in all 'git ls-files' paths."
    echo "  Implicitly sets a word boundary on either side of the regex."
    echo "  Thus add \w* on either side to weaken it up."
    echo
    echo "  Options (can be put before or after the regex):"
    echo "   -i      case-insensitive"
    echo "   --for   instead of 'impl Foo', search for 'impl .. for Foo'"
    echo
    echo "  Also see: search, ci, _keyword_identifier_search"
    exit 1
}


opt_for=''
opts=(--show-function)
args=()

for arg in "$@"; do
    case "$arg" in
        -i)
            opts+=(-i)
            ;;
        --for)
            opt_for=1
            ;;
        *)
            args+=("$arg")
            ;;
    esac
done

if [ ${#args[@]} -ne 1 ]; then
    usage
fi


if [ "$opt_for" = 1 ]; then
    search "${opts[@]}" '\bimpl\b\s*(?:<[^<>]*>)?\s*\w+\s*(?:<[^<>]*>)?\s+for\s+\b'"${args[@]}"'\b'
else
    search "${opts[@]}" '\bimpl\b\s*(?:<[^<>]*>)?\s*\b'"${args[@]}"'\b'
fi

