#!/usr/bin/perl -w

# Don Nov  4 09:50:11 MET 2004
(my $email='pflanze%gmx,ch')=~ tr/%,/@./;

use strict;

my $sleeptime=5;

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname prg arguments

  start prg with arguments and restart it every $sleeptime seconds,
  printing the exit code it returned.

  (Christian Jaeger <$email>)
";
exit @_ ? 1 : 0;
}

my @args;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
#     } elsif (/^--?X(?:XXX(?:=(.*))?)?$/) {
#         if (defined $1) {
#             $XXX=$1
#         } else {
#             $XXX=$ARGV[++$i] or usage "missing argument for '$_' option";
#         }
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
	push @args, @ARGV[$i..$#ARGV];
	last;
    }
}
usage unless @args;

while(1) {
    system @args;
    print STDERR "$myname: program '$args[0]' ".(($?==0 or $? > 255) ?
						 "exited with exit code ".($? >> 8)
						 :
						 "was killed by signal ".($? & 255)
						 )."\n";
    sleep $sleeptime;
}
