#!/usr/bin/perl -w

# Sat Nov 27 18:19:11 EST 2010
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

our $default_start = 1;
our $delim = "\t";

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname [start [file... ]]

  Prepend numbering to lines read from stdin to stdout, or the given
  'file'(s) (continues numbering across files!).

  'start' is $default_start by default.

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   ) or exit 1;

our $start= @ARGV ? shift @ARGV : $default_start;

$start=~ /^\d+\z/ or usage "not a number: '$start'";

my $n=$start;
while (<>) {
    print $n, $delim, $_
      or die "print to stdout: $!";
    $n++;
}
close STDIN or die $!;
close STDOUT or die $!;

