#!/usr/bin/perl -w

(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname [options] regex [options]

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

usage if (! @ARGV
	  or
	  (@ARGV==1 and $ARGV[0]=~ /^--?h(elp)?\z/));

use Chj::singlequote 'singlequote_sh';
use Chj::xperlfunc 'xexec';

xexec ("find -name 'Kconfig*' -print0|xargs -0 egrep "
       .
       join(" ",
	    map {
		singlequote_sh $_
	    }
	    map {
		s/^CONFIG_//; $_
	    }
	    @ARGV));
