#!/bin/bash

usage(){
    echo "$0 regex"
    echo "  egrep for regex in all configure help files (Kconfig)"
    echo "  in linux-2.6 source trees."
    echo "  The current working dir must be the toplevel dir of an"
    echo "  unpacked linux source tree."
    exit 1
}

if [ $# -lt 1 -o "A$1" == "A-h" -o "A$1" == "A--help" ]; then
    usage
fi

find -name 'Kconfig*' -print0|xargs -0 egrep "$@"
