#!/usr/bin/perl -w

# Wed Jun 11 07:01:16 CEST 2008
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

# really f*cking fricking how I EVER so now never. this here to solve me.

use strict;

our $boot= "/boot";


$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname [ -c ] kernel_version

  Options:
  -c  create, if none existed for this kernel version before
  -v  verbose
  --dry-run  only show

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
our $opt_create;
our $opt_dry;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   "c"=> \$opt_create,
	   "dry-run"=> \$opt_dry,
	   ) or exit 1;
usage unless @ARGV==1;

our ($kernel_version)=@ARGV;

use Chj::xperlfunc;

sub Do {
    my $proc=shift;
    my (@cmd)=@_;
    if ($verbose or $opt_dry) {
	use Chj::singlequote 'singlequote_many';
	print STDERR ($opt_dry ? "would run " : "running ").$proc." ".singlequote_many (@cmd)."\n";
    }
    unless ($opt_dry) {
	no strict 'refs';
	# rely on $proc containing a string 'yay' ha.
	$proc->(@cmd)
    }
}


our @cmd=("update-initramfs",
	  ($opt_create ? "-c" : "-u"),
	  ($verbose ? "-v" : ()),
	  "-k",
	  $kernel_version);

Do xxsystem=> @cmd;

Do xsystem=> "mvnumber", "$boot/initrd.img.old";#well.
Do xrename=> "$boot/initrd.img", "$boot/initrd.img.old";
Do xsymlink=> "initrd.img-$kernel_version", "$boot/initrd.img";


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
