#!/bin/sh

# cj Thu, 19 Aug 2004 22:47:40 +0200
# experimental.

# make interactive command stuff defined. hrm executes mesg again and such.
if [ -f ~/.bashrc ]; then PS1="loop" . ~/.bashrc; fi

#cmd="$@"
while true; do
    #eval "$cmd"
    eval $@
    #hm, manche sachen gehen einfach kaputt so, muss whitespace zwischen ' ' backslashen und so.
    # ' gehen verloren bei ein-string-machen. wohl.
    #"$@" $@ auch nix. MUSS es die shell parsen lassen
    #eval "$1"
    # NA, wenn ich es so aufrufe dann geht es ja bravissimo:
    # loop "show_listeners|perl -wne 's/p/O /g;print' ; echo ; sleep 2"
    # und dies tut zwei nacheinander. Luschtigerweise, wenn ich ; nach sleep 2 weglasse, kriegt sleep echo Ende als argumente.
    # root@lombi root# loop "shift; show_listeners|perl -wne 's/p/O /g;print' ; echo ; sleep 2;" "echo Ende; sleep 1"

done
