#!/bin/bash

set -eu

usage() {
    echo "$0 [wholedisk]"
    echo
    cat <<EOF
<jelly> chrissbx: use kpartx instead
<jelly> chrissbx: you'll need to destroy the kpartx-generated devices first if you decide to losetup -d
EOF
    exit 1
}

if [ $# -eq 1 ]; then
    arg=$1
    if [[ "$arg" = "-h" || "$arg" = "--help" ]]; then
        usage
    else
        path=$(chase "$arg")
	kpartx -av "$path"
	echo "Ok. Look for them in /dev/mapper/ ! Afterwards, run:"
        echo "  kpartx -d $(printf '%q' "$path")"
    fi
else
    usage
fi
