#!/bin/sh

set -eu

if [ -f /usr/sbin/lsof ]; then
    lsof=/usr/sbin/lsof
elif [ -f /usr/bin/lsof ]; then
    lsof=/usr/bin/lsof
else
    echo "don't know where lsof is"
    exit 1
fi

exec "$lsof" -nP "$@"

# -n = no host names
# -P = no port names
