#!/bin/sh

#exec /usr/sbin/lsof -nP "$@"
# Mon, 29 May 2006 17:39:03 +0200: das war mal. nun haben debian das nach /usr/bin/ verschoben.

if [ -f /usr/sbin/lsof ]; then
    lsof=/usr/sbin/lsof
elif [ -f /usr/bin/lsof ]; then
    lsof=/usr/bin/lsof
else
    echo "don't know where lsof is"
fi

exec "$lsof" -nP "$@"

# -n = no host names
# -P = no port names
