#!/bin/sh

# Nach Grösse sortiertes offenes File suchen:
# 
# COMMAND     PID        USER   FD   TYPE     DEVICE     SIZE      NODE NAME
# init          1        root  cwd    DIR        8,2      560         2 /
# init          1        root  rtd    DIR        8,2      560         2 /
# init          1        root  txt    REG        8,2    28008      5840 /sbin/init
# init          1        root  mem    REG        8,2    90210    107879 /lib/ld-2.2.5.so
# syslogd     157        root    7w   REG        8,2     9555     77377 /var/log/mail.log
# syslogd     157        root    8w   REG        8,2        0    125825 /var/log/user.log
# 
# 

lsof -n |grep ' REG '|awk '{print $1,$7,$9}'|sort -k 2 -n -r|uniq|less

# smbd 30362373 /tmp/avfspl.0.log
# smbd 30362373 /tmp/avfspl.0.log
# proftpd 30362373 /tmp/avfspl.0.log
# httpd 15469902 /var/log/apache/access.log.1
# 
# apache-pe 9697743 /var/log/apache-perl/error.log
