#!/usr/bin/perl -w

#cjaeger9.9.2000


my $trash;
if ($ENV{TRASHCAN}) {
	$trash= $ENV{TRASHCAN}
} elsif (-e $ENV{HOME}."/Desktop/Trash/") {
	$trash=$ENV{HOME}."/Desktop/Trash/";
} elsif (-e $ENV{HOME}."/Desktop/Mülleimer/") {
	$trash=$ENV{HOME}."/Desktop/Mülleimer/";
} elsif (-e $ENV{HOME}."/.trash/") {
    $trash=$ENV{HOME}."/.trash/";
} elsif (-e $ENV{HOME}."/.Trash/") {
    $trash=$ENV{HOME}."/.Trash/";
} else {
	die "Konnte Deinen Trashcan nicht finden. ";
}

exec qw(/bin/ls -lrt --show-control-chars --color ),@ARGV,"--",$trash;
