#!/bin/bash
set -meuo pipefail
IFS=

if [ $# = 0 ]; then
    dir=.
elif [ $# = 1 ]; then
    dir="$1"
else
    echo "usage: $0 [dir]"
    exit 1
fi

lst -lrt --ignore '/\.(METADATA-v2|git)(/|$)' --ignore '~$' --find-dir "$dir"
