#!/usr/bin/perl -w

# Sam Sep  1 14:26:00 CEST 2007
(my $email='pflanze%gmx,ch')=~ tr/%,/@./;

use strict;

use Chj::ruse;#ach aber ruse von mailmoverlib geht dann doch nid. nid weils required wirdblos. sondern weils class array nutztr und das  problem  meldet  gag.  weils nid in sep file isch gell.klro.

my ($mydir, $myname);
BEGIN{
    $0=~ /(.*?)([^\/]+)\z/s or die "?";
    ($mydir, $myname)=($1,$2);
    require "$mydir/mailmoverlib.pm";
    #require "$mydir/mailmover_autoreply.pm" if $do_send_autoreply;
}

sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname ..

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

my @args;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
#     } elsif (/^--?X(?:XXX(?:=(.*))?)?$/) {
#         if (defined $1) {
#             $XXX=$1
#         } else {
#             $XXX=$ARGV[++$i] or usage "missing argument for '$_' option";
#         }
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}
#usage unless @args==1;

#use Chj::xopen 'xopen_read';
#our $f= xopen_read $args[0] if @args;
#nö.

my ($mail,$foldername,$type,$important);
sub init {
    ($mail,$foldername,$type,$important)= analyze_file $args[0] if @args;
}
init;

use Chj::repl;repl;
