#!/usr/bin/perl -w

# Die Jan 21 23:03:15 CET 2003

use strict;

$0=~ /([^\/]+)$/s or die "?";
my $myname=$1;
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname
  Filter text cut from a 'Depends:' line or the like of a deb
  package from stdin to stdout.
";
exit @_ ? 1 : 0;
}

my @files;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @files, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
    } elsif (/^-/) {
    	warn "Unknown option '$_'\n";
    	usage(1)
    } else {
    	push @files, $_
    }
}
usage if @files;

local $/;
my $a= <STDIN>;

$a=~ s/\(.*?\)//sg;
$a=~ s/>//sg;
$a=~ s/\s*\|\s*/|/sg;
my @multi;
my @rest= map {s/\|/ | /sg ? do{push @multi;""} : "$_ "} split /[\s,]+/,$a;

print STDERR map {"$_\n"} @multi if @multi;
print @rest;

