#!/bin/bash

set -eu

md=`mdsha "$@"`

echo "$md"

echo "$md" | perl -wne 'm/^(\w+)/ or die "no match for: $_"; print "http://www.google.com/search?ie=UTF8&q=$1\n"' | myxargs ${BROWSER-local-webbrowser}

#^ not quoting BROWSER variable on purpose.
# ok ?.
# for arguments, you know .. hm h ..
