#!/bin/bash

set -eu

stdout=`tty`

mdsha "$@" | tee "$stdout" | perl -wne 'm/^(\w+)/ or die "no match for: $_"; print "http://www.google.com/search?ie=UTF8&q=$1\n"' | myxargs "${BROWSER-galeon-chrissbx}"
