#!/usr/bin/perl -w

# Fre Aug  6 01:30:02 MEST 2004
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname [file(s)]
  or stdin.
  Options:
  -h headername   print header value(s?)

  (Christian Jaeger <$email>)
";
exit @_ ? 1 : 0;
}

use Getopt::Long;
our $verbose=0;
our $opt_h;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   "h|headers=s" => \$opt_h,
	   ) or exit 1;
usage unless @ARGV;


use MIME::Parser;
use Chj::xopen 'xopen_read';
use Chj::singlequote;

my $parser = new MIME::Parser;
$parser->output_under("/tmp");# IMPORTANT! or it will put them to cwd.

sub parsemsg {
    my ($fh)=@_;
    my $ent= $parser->parse($fh);
    #use Data::Dumper;
    #print Dumper $ent;
    $ent
}

if (@ARGV) {
    for(@ARGV) {
	print "File ".singlequote($_).":\n";
	my $f=xopen_read $_;
	my $ent=parsemsg($f);
	##unfinished:
	if ($opt_h){
	    #show header
	    my $head=$ent->head;
	    my @vals= $head->get($opt_h);
	    if (@vals==0) {
		print "no such header ".singlequote($opt_h)."\n";
	    } elsif(@vals==1){
		print "one such header ".singlequote($opt_h).": ".singlequote($vals[0])."\n";
	    } else {
		my $i=0;
		for(@vals){
		    print "$i. header ".singlequote($opt_h).": ".singlequote($_)."\n";
		    $i++;
		}
	    }
	}else {
	    die "unknown command requested <--- unfinished";
	}
    }
}
else {
    parsemsg(*STDIN{IO});
}
