#!/bin/bash

set -eu

fkm () {
    find /lib/modules/"$(uname -r)"/ -iname "*$1*.ko*" | cut -d/ -f5-
    if [[ "$(uname -r)" != "$(/bin/ls -1 /lib/modules/ | head -1)" ]]; then
	echo "Did you reboot after updating your kernel?"
    fi
}

old () {
    exec /sbin/modprobe "$@"
}

#if [ $# -eq 1 && $# -le 2 ]; then

if [ $# -ge 1 ]; then
    if [ $# -le 2 ]; then
	if [ "$1" = -l ]; then
	    fkm "${2-}"
	else
	    old "$@"
	fi
    else
        old "$@"
    fi
else
    old "$@"
fi

