#!/bin/bash

#if [ $# -le 2 && "$1" = "-l" ] ; then
#what's up with that??^
if [ $# -le 2 ]; then
    shift
    find /lib/modules/"$(uname -r)"/ -iname "*$1*.ko*" | cut -d/ -f5-
    if [[ "$(uname -r)" != "$(/bin/ls -1 /lib/modules/ | head -1)" ]]; then
	echo "Did you reboot after updating your kernel?"
    fi
else
    exec /sbin/modprobe "$@"
fi
