#!/usr/bin/perl -w

# Mit Mai 14 06:36:56 MEST 2003

use strict;

use Chj::xperlfunc ":all";

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname file(s) dirpath

  Prefix the filename in dirpath with \`dat\` and move the files there.
";
exit(@_ ? 1 : 0);
}

my @files;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @files, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @files, $_
    }
}
usage unless @files;

my $dir= pop @files;

my $date=`dat`; chomp $date;

my $dn = dirname $dir;
my $bn = basename $dir;
my $newdir = "$dn/$date $bn";

mkdir $newdir
    or -e $newdir
    or die "mkdir '$newdir': $!";

xsystem "mv", "-i", "--", @files, $newdir;
