#!/bin/sh
settitle 'mysqldoc'
if [ -f /usr/local/mysql/docs/manual_toc.html ]; then
    exec links-local /usr/local/mysql/docs/manual_toc.html
else 
    exec links-local /usr/share/doc/mysql-doc/index.html
fi
