#!/usr/bin/perl -w

use strict;
$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);

# symlink based argument processing:
our $no_run_if_empty=1;

{
    my $name= $myname;
    $name=~ s/^([^-]+)// or die "I'm given an in valid name '$myname'";
    #my $onlyname= $1;
    if ($name) {
	my $optionpart=$name;
	if ($name=~ s/-run-if-empty//) {
	    $no_run_if_empty=0;
	}
	#if ($name=~ s/-oneinvocation//) {
	# well, we'll assume this always anyway, right? why not.
	if ($name) {
	    die "don't understand option part '$optionpart'";
	}
    }
}

use Chj::App::Myxargs qw(options_and_cmd myxargs);

my $options_and_cmd= options_and_cmd();
$$options_and_cmd{no_run_if_empty}= $no_run_if_empty;
myxargs $options_and_cmd;

