#!/bin/bash

set -eu

usage () {
    echo "$0 <user> on|off"
    echo "  enable/disable internet access for the given user"
    exit 1
}


if [ $# -ne 2 ]; then
    usage
fi

user="$1"
onoff="$2"

DA=""
case "$onoff" in
    off)
    if iptables -L -t filter|grep --quiet "owner UID match $user "; then
	echo "already off"
	exit 1
    fi
    DA=-A
    ;;
    on)
    DA=-D
    ;;
    *)
    echo "invalid on/off setting '$onoff'"
    usage
    ;;
esac

iptables -t filter $DA OUTPUT -m owner --uid-owner "$user" -j REJECT
