#!/bin/bash

# Netcat is an utterly broken API: traditional netcat and nc.openbsd
# don't share a common set of options to work correctly as a client
# that copies all data from the server regardless of its own stdin,
# thus need to differentiate this way:

set -eu

if [[ $# -ne 2 || $1 = "-h" || $1 = "--help" ]]; then
    echo "usage: $0 server port"
    exit 1
fi

if have nc.traditional; then
    nc.traditional "$@"
elif have nc.openbsd; then
    # nc.openbsd neither works without -q option nor supports -q-1,
    # nor does -q0 mean infinite, thus need to use a big enough number
    # of seconds
    # Wed 19 Oct 22:31:29 CEST 2022: now -q999999999 doesn't work anymore.
    # Have they fixed it? In a backwards incompatible way?
    nc.openbsd "$@"
else
    echo "cannot find nc.traditional nor nc.openbsd" >&2
    exit 1
fi


