#!/bin/bash 

if [ $# -lt 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
    echo "$0 [-z] server [ port ]"
    echo "  connects to server/port (port is some default+uid by default)"
    echo "  and fetches a tar, asks for confirmation and unpacks it."
    echo "  If the -z option is given, the stream is assumed to be gzipped."
    exit 1
fi

z=""
if [ "$1" = "-z" ]; then
    z="-z "; shift
elif [ "$1" = "--" ]; then
    shift
fi

SERVER="$1"
if [ "$2" ]; then
    PORT="$2"
else
    if [ ! "$PORT" ]; then
	PORT=$((14123+$UID))
    fi
fi

tfile=`tempfile`


netcat -q 1 "$SERVER" "$PORT" | multifeed '|' sh -c 'exec md5sum >&2' '&' cat  > "$tfile"

echo -n "Ok? "

read ans

#echo "HABE <$ans> GELESEN"
#if [ "`echo "$ans" | cut -c1,1 | grep -i '[jy]'`" ]; then
#if [ "`echo $ans | cut -c1,1 | grep -i '[jy]'`" ]; then
#if [ "`echo "$ans" | egrep -i '^[\n ]*[jy]'`" ]; then
#if perl -ne 'exit !! (shift =~ /^\s*[jy]/i)' "$ans"; then   nein, frisst argumente
if ! echo "$ans" | perl -wne 'exit 1 if /^\s*[jy]/i'; then
    tar x ${z}-f "$tfile"
else
    echo "Canceled."
fi

rm -f "$tfile"
