#!/bin/bash 

set -eu

if [ $# -lt 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
    echo "$0 [-z] server port"
    echo "  then needs the pw on stdin."
    echo "  -> See netoffer instead."
    exit 1
fi

z=""
if [ "$1" = "-z" ]; then
    z="-z "; shift
elif [ "$1" = "--" ]; then
    shift
fi

SERVER="$1"
PORT="$2"

# can't let gpg read it by itself because that messes up single
# reading (probably too-greedy reading by the shell?), so:

pwfile=`tempfile`
cat > "$pwfile"

netcat -q 1 "$SERVER" "$PORT" \
    | gpg -q -d --batch --passphrase-file "$pwfile" \
    | tar x ${z}-f -

rm "$pwfile"
