#!/bin/bash

set -eu

usage() {
    echo "$0 [-z|-Z] files_to_offer"
    echo "  offer files, encrypted"
    echo "  -z  use gzip compression instead of lzop"
    echo "  -Z  don't use compression"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
elif [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

z="--lzop"
if [ "$1" = "-z" ]; then
    z="-z "; shift
elif [ "$1" = "-Z" ]; then
    z=""; shift
elif [ "$1" = "--" ]; then
    shift
fi

if [ ! "${PORT-}" ]; then
    PORT=$((14123+$UID))
fi


ip=`publicip -f`

passwdgen | tee >(
{
echo "--Run:--"
echo "echo `cat` | netfetch $z$ip $PORT"
} >&2
) | {
tar c ${z} --sparse -f - "$@" \
    | gpg -z0 -c --batch --force-mdc --passphrase-fd 9 \
    | netcat-serve-on-port "$PORT" 
} 9<&0 </dev/null
