#!/bin/bash

set -eu

usage() {
    echo "$0 [-z] files_to_offer"
    echo "  offer files, encrypted"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
elif [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

z=""
if [ "$1" = "-z" ]; then
    z="-z "; shift
elif [ "$1" = "--" ]; then
    shift
fi

if [ ! "${PORT-}" ]; then
    PORT=$((14123+$UID))
fi

# See comments about brokenness of netcat 'API' in netfetch.

if have nc.traditional; then
    NETCAT_SERVE_ON_PORT="nc.traditional -q 0 -l -p"
elif have nc.openbsd; then
    NETCAT_SERVE_ON_PORT="nc.openbsd -q 0 -l"
else
    echo "can't find either nc.traditional or nc.openbsd" >&2
    exit 1
fi


ip=`publicip -f`

passwdgen | tee >(
{
echo "--Run:--"
echo "echo `cat` | netfetch $z$ip $PORT"
} >&2
) | {
tar c ${z}-f - "$@" \
    | gpg -z0 -c --batch --force-mdc --passphrase-fd 9 \
    | $NETCAT_SERVE_ON_PORT "$PORT" 
} 9<&0 </dev/null
