#!/bin/bash

set -euo pipefail
IFS=

usage() {
    echo "usage: `basename "$0"` [-z|-Z]"
    echo 
    echo "  Start one-shot service to receive files, encrypted. Run"
    echo "  in directory to use as the base dir for the reception,"
    echo "  then follow the instructions it prints (i.e. run 'netsend'"
    echo "  with the files to copy on the other side, then copy"
    echo "  and paste the token)".
    echo
    echo "  -l  use lzop compression (default)"
    echo "  -z  use gzip compression instead of lzop"
    echo "  -Z  do not use compression"
    echo
    echo " Also see \`netoffer\`."
    echo
    exit 1
}

if [ $# -gt 1 ]; then
    usage
fi

zz="-l" # for netfetch
z="--lzop" # for tar

if [ $# -eq 1 ]; then
    if [[ "$1" = "-h" || "$1" = "--help" ]]; then
	usage
    fi
    if [ "$1" = "-z" ]; then
	zz="$1"
	z="-z "
	shift
    elif [ "$1" = "-Z" ]; then
	zz="$1"
	z=""
	shift
    elif [ "$1" = "-l" ]; then
	zz="$1"
	z="--lzop"
	shift
    elif [ "$1" = "--" ]; then
	shift
    fi
fi

if [ $# -ne 0 ]; then
    usage
fi


if [ ! "${PORT-}" ]; then
    PORT=$((14123 + UID))
fi


ip=`publicip -f`

pass=`passwdgen 24`

{
    echo "--Run \`netsend  files-you-want-to-transmit..\` on the other host,"
    echo "  then copy paste the following line:"
    echo "NETSEND $pass $zz $ip $PORT"
} >&2


echo "$pass" | {
    {
	netcat-receive-on-port "$PORT" \
	    | gpg -q -d --batch --force-mdc --passphrase-fd 9 \
	    | tar -x ${z} --sparse -f -
    } 9<&0
}
