#!/usr/bin/perl -w

use strict;
BEGIN {
    $0=~ /(.*?)([^\/]*)$/s;
    unshift @INC, $1;
    require 'newperl.pl';
}



sub usage {
    $0=~ /([^\/]*)$/;
    print "$1 some/path/perlfile

  Macht neues ausführbares Perlskript im \$EDITOR auf.
";
    exit;
}

usage() unless @ARGV;

my @paths;
for (@ARGV) {
    if (/^--?h(elp)?$/) {
	usage();
    } else {
	create ($_);
    }
}

edit (15, @paths);


sub create {
    my ($path)=@_;
	
    if (-e $path) {
	warn "Datei $path existiert bereits!\n";
	push @paths,$path;# trotzdem editieren
    } else {
	$path=~ /(.*?)[^\/]*$/ or die;
	my $folder= $1;
	if (length $folder) {
	    if (-d $folder) {
		# ok
	    } else {
		$|=1;
		print "Der Ordner '$folder' existiert nicht. Kreieren? [j/n] ";
		my $a=<STDIN>;
		if ($a=~ /^[jy]/) {
		    system "/bin/mkdir",$folder;
		} else {
		    warn "Cancel.\n";
		    return;
		}
	    }
	}
	if (open OUT,">$path") {
	    my $copy= copy();
	    print OUT <<"END" or warn "Fehler beim Schreiben: $!";
#!/usr/bin/perl -w

$copy
#
# \$Id\$

use strict;

use vars qw();


END
# Könnte noch  use vars qw{$VERSION};  und  $VERSION = '0.00'; reintun. Aber naja?
# oder müsste ich eh BEGIN { $DBI::VERSION= "..." } machen?

	    close OUT;
	    system "/bin/chmod","+x",$path;
	    push @paths,$path;
	} else {
	    warn "Konnte Datei '$path' nicht öffnen: $!\n";
	}
    }
}

