#!/usr/bin/perl -w

# Mit Nov  5 15:41:05 MET 2003
(my $email='ch%christianjaeger,ch')=~ tr/%,/@./;

use strict;
use Chj::Parse::Hexdump;

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname
  currently only stdin to stdout

  (Christian Jaeger <$email>)
";
exit(@_ ? 1 : 0);
}

my @args;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
#     } elsif (/^--?X(?:XXX(?:=(.*))?)?$/) {
#         if (defined $1) {
#             $XXX=$1
#         } else {
#             $XXX=$ARGV[++$i] or usage "missing argument for '$_' option";
#         }
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}
usage if @args;

my $parser= new Chj::Parse::Hexdump::Parser;

while (<STDIN>) {
    $parser->add($_);
    print $parser->fetch;
}
