#!/bin/sh

# jaeger-ethlife.ethz.ch Sun, 15 Jun 2003 20:13:17 +0200

DEV="$1"

if [ ! "$DEV" ]; then
    echo "Bitte dev angeben!"
    exit 1
fi

if [ ! "`echo "$DEV" | grep -F /`" ]; then
    DEV="/dev/$DEV"
fi

DEVVOLL="`chase "$DEV"`"

if [ ! "$DEVVOLL" ]; then
    echo "Looks like $DEV does not exist, terminating."
    exit 1
else
    # strip /dev part, since mdstat does not contain it
    DEVVOLL="`echo "$DEVVOLL"|cut -d/ -f3-`"
fi


#echo "Checking '$DEV' aka '$DEVVOLL'.."
echo "---- Checking '$DEV' aka '$DEVVOLL': --------------------------------------------------------------------------------------------------------------------------------------------------------------------"|cut -b1-$COLUMNS

#grep "$DEV" /etc/fstab /proc/swaps /proc/mounts /proc/mdstat /etc/rawtab
#grep "$DEVVOLL" /etc/fstab /proc/swaps /proc/mounts /proc/mdstat /etc/rawtab

for f in /etc/fstab /proc/swaps /proc/mounts /proc/mdstat /etc/rawtab; do
    echo $f:
    if [ -e "$f" ]; then
	cat "$f" | egrep "($DEV|$DEVVOLL)"
    else
	echo " - (file does not exist)"
    fi
    echo
done

# this is rather quick and dirty, right?:
echo vgdisplay:
vgdisplay -v 2>/dev/null | egrep "($DEV|$DEVVOLL)"
echo

# dito, not even sure this will find something sensibly:
echo loop devices:
losetup -a | egrep "($DEV|$DEVVOLL)"
echo

echo "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"|cut -b1-$COLUMNS
echo "  (Hint: use raw -qa to find out about possible raw device bindings, "
echo "   unless you have all mappings in /etc/rawtab.)"
