#!/bin/sh

# cj Sam_Jan_15_211006_MET_2005-Sat, 15 Jan 2005 22:12:11 +0100

cat <<'EOF'|less
cj, from man passwd (woody)

       passwd [-f|-s] [name]
       passwd [-g] [-r|R] group
       passwd [-x max] [-n min] [-w warn] [-i inact] name
       passwd {-l|-u|-d|-S|-e} name

userinfo:
-f 	The -f option makes
	       passwd  call chfn to change the users gecos information.
-s 	The -s option makes passwd call chsh to change the users shell.
These two options are only meant for compatiblity, since the other programs can be called directly.

groups:
-g	When  the -g option is used, the password for the named group is changed.
-r	The -r option is used with the -g
	       option to remove the current password from the  named  group.
-R	The -R option is used with the -g option to restrict the
	       named group for all users.

Password expiry information:
-x	The  -x option is used to set the maximum number of days a
	       password remains valid.
-n	The  -n  option  is used to set the minimum number of days before a password 
	       may be changed.
-w 	The -w option is used to set the number of days of warning the user will
	       receive before their password will expire.
-i	The -i option is used to disable an account after the password has been 
	       expired for a number of days.

Account maintenance:	PS. ja, Optionen gehen auch NACH usernamensangabe.
-l	lock
-u	unlock
-e	immediately expire
-d	delete password (make it empty)... Use caution
	    	with this option since it can make an account not require  a  
       		password at all to login, leaving your system open to intruders.  ????!
-S	give account status information

EOF
