#!/usr/bin/perl -w

# Mon Nov  5 13:42:46 MET 2007
(my $email='pflanze%gmx,ch')=~ tr/%,/@./;

use strict;

our $length_in_bytes= 5;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    my $_length_in_bits= $length_in_bytes*8;
    print "$myname [length_in_bytes]

  Generate password of length_in_bytes of randomness/entropy(?)/data
  (by default, $length_in_bytes bytes ($_length_in_bits bits)).

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   ) or exit 1;
usage if @ARGV>1;
if (@ARGV) {
    ($length_in_bytes)=@ARGV
}

use Chj::Random::Formatted 'random_passwd_string';

print random_passwd_string ($length_in_bytes),"\n"
  or die $!;

close STDOUT
  or die $!;
