#!/bin/bash

word="$1"
shift

if [ -z "$word" ] || [ $# -eq 0 ]; then
    echo "usage: $0 word dir"
    echo "  greps all .pm files for the occurence of the given \w+,"
    echo "  ignoring lines beginning with whitespace and the #."
    echo "  (-> only about)"
    exit 1
fi

find "$@" -name "*.pm" -print0 \
    | xargs -0 grep -F "$word" \
    | perl -we '
while (<STDIN>) { 
    print if not( /\.pm:\s*#/) and /\b\Q$ARGV[0]\E\b/ 
}' -- "$word"

