#!/bin/sh

usage () {
    echo "$0 fieldno"
    echo "  filters stdin to stdout, outputting only filed no. filedno, like"
    echo "  awk \"{print \\\$\$fieldno}\""
    echo
    echo " See also: fields"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

fieldno="$1"

awk "{print \$$fieldno}"
