#!/usr/bin/perl -w

# Fre Apr 27 13:30:09 CEST 2007

use strict;

use Chj::App::Maillogfilterapp;

maillogfilterapp (
		  "/var/log/qmail/current",
		  '/var/log/qmail/{current,@*}',
		  "|tai",
		  "--flush",
		  );
