#!/usr/bin/perl -w

# Fre Apr 27 13:30:09 CEST 2007
(my $email='pflanze%gmx,ch')=~ tr/%,/@./;

use strict;

my $nfiles=3;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname

  Options:
  -n|--n-files n   use the n instead of $nfiles newest log files
  -f               follow mode

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;

our $verbose=0;
our $DEBUG=0;
our $opt_f;
GetOptions("verbose"=> \$verbose,
	   "d|debug"=>\$DEBUG,
	   "help"=> sub{usage},
	   "f|follow"=> \$opt_f,
	   "n|n-files=i"=> \$nfiles,
	   ) or exit 1;
usage if @ARGV;

use Chj::xperlfunc;

if ($opt_f) {
    xexec
      "fasttail /var/log/qpsmtpd/qpsmtpd.log| $mydir/maillogfilter";
} else {
    xexec
      'myzcat `ls -rt /var/log/qpsmtpd/qpsmtpd.log*|tail -'
      .$nfiles
      .'`|'
      .$mydir
      .'/maillogfilter|less';
}
