#!/bin/sh

if [ $EUID -gt 0 ]; then
	echo "Bitte als root laufen lassen"
else 
	if [ "$1" ]; then
		tmpfile="`tempfile`"
		aumix -S -f "$tmpfile"
		sighandler() {
		    #( sleep 3; aumix -L "$tmpfile" )&
		    # gar ned nötig zu forken. signals gelangen offenbar doch zu subprozessen(?).
		    aumix -L "$tmpfile" > /dev/null
		    rm -f "$tmpfile"
		    # och und weil das obige nicht wirklich richtig oder gar nicht funktionniert, noch:
		    aumix -v 10 # line out
		    aumix -p 10 # eingebaute lautsprecher
		    exit 0
		}
		trap sighandler 1 2 3 15
		aumix -v 0
		aumix -p 0
		#aumix -m 100 # strangely isches eben NICHT microphone setting das sich auswirkt
		# und auch nicht -i  line in.  sondern:  line
		aumix -l 55

		# und seit alsa muss ich machen:
		aumix -l R
		# und seit 8.4.04:
		aumix -l 50  # scheint muss NACH -l R nochmals setzen? oder?


		# aha für external mic?:
		#aumix -i 0
		#aumix -m 100
		# geht nicht.

		brec -d /dev/sound/dsp -s 22050 -b 16 -r \
		| nice --18 bfr --minimum 0 \
		| nice --16 oggenc -C 1 -R 22050 -q 1 - -o "$1"
		# -q 1 hatte ich vor 29.2.04.
		# -q 0 scheint auch ok aber hörbar instabiler und ev auch höhennehmend.
		# -q -1 tönt etwa wie spx
		# das tragische ist, dass 0 und -1 scheints genau gleichviel platz brauchen (wie 1)
	else
		echo "Bitte filename angeben. Ist für Mac Powerbook G3 gemacht, möglicherweise ist endianness auf PC falsch."
	fi

fi
