#!/bin/sh

if [ $EUID -gt 0 ]; then
	echo "Bitte als root laufen lassen"
else 
	if [ "$1" ]; then
		tmpfile="`tempfile`"
		aumix -S -f "$tmpfile"
		sighandler() {
		    #( sleep 3; aumix -L "$tmpfile" )&
		    # gar ned nötig zu forken. signals gelangen offenbar doch zu subprozessen(?).
		    aumix -L "$tmpfile" > /dev/null
		    rm -f "$tmpfile"
		    exit 0
		}
		trap sighandler 1 2 3 15
		aumix -v 0
		aumix -p 0
		#aumix -m 100 # strangely isches eben NICHT microphone setting das sich auswirkt
		# und auch nicht -i  line in.  sondern:  line
		aumix -l 100
		# und seit alsa muss ich machen:
		aumix -l R
		brec -d /dev/sound/dsp -s 22050 -b 16 -r \
		| nice --18 bfr --minimum 0 \
		| nice --16 swapendianness \
		| nice --16 bfr --minimum 0 \
		| nice --16 gsm -e > "$1"
	else
		echo "Bitte filename angeben. Ist für Mac Powerbook G3 gemacht, möglicherweise ist endianness auf PC falsch."
	fi

fi
