#!/usr/bin/perl -w

# Thu Nov 20 15:25:06 CET 2008
(my $email='christian-novo%jaeger,mine,nu')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);

use Chj::App::Recordip;

our $datadir= datadir (1);

sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    my $datadir_path= $datadir->path;
    print "$myname

  Show ip's recorded in '$datadir_path', as an -E regular
  expression.

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   ) or exit 1;
usage if @ARGV;

our ($ips,$attrs)= $datadir->ip_and_attr_stores;


#use Chj::ruse;
#use Chj::Backtrace;

use Chj::FileStore::MIndex::NonsortedIterator;
our $iter= Chj::FileStore::MIndex::NonsortedIterator->new($ips,sub {
							      my ($k)=@_;
							      not ($k=~ /^192\.168\./)
							  });##HU why does the filter not work ???


use Chj::xopen ':all';
our $ip_re= qr/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/;
#^^well ipv6 and so on etc usw .... and lib ...

our @ips= do {
    # older/other known ip's?:
    my @res= eval {
	my $f=xopen_read "$ENV{HOME}/var/recordip.list";
	#$f->xnread ehr. for commented files ya know. he.
	my @ips;
	while (<$f>) {
	    chomp;
	    next if /^\s*#/||/^\s*\z/s;
	    # well. accept comments after ip, too:
	    s/#.*//;
	    if (/\s*($ip_re)\s*\z/s) {
		push @ips, $1;
	    } else {
		warn "unintelligible line: '$_'";
	    }
	}
	@ips
    };
    if (ref $@ or $@) {
	warn "warning: $@";
	()
    } else {
	@res
    }
};
while (my $k= $iter->next_key) {
    #print "$k\n"
    #  or die $!;
    push @ips, $k
      if not ($k=~ /^192\.168\./)
}
##HMMM.uniq.hmmm.

print "'^(".join("|",map {
    my $s=$_;
    $s=~ s/\./\\./sg;
    $s
} sort @ips).")'\n"
  or die $!;

#use Chj::repl; repl;
