#!/bin/sh

if [ $EUID -gt 0 ]; then
	echo "Bitte als root laufen lassen"
else 

	if [ "$1" ]; then
		brec -d /dev/sound/dsp -s 22050 -b 16 -r | nice --17 sox -t raw -r 22050 -s -w -c 1 -x - -t wav -r 22050 -|nice --16 /home/chrissnd/bin/lame --voice  -m m - "$1"
	else
		echo "Bitte filename angeben"
	fi

fi
