#!/bin/bash

set -eu

usage () {
    echo "$0 rfcnumber"
    echo "  Give an RFC number (number only)."
    exit 1
}

if [ $# -eq 1 ]; then
    if [[ $1 = "-h" || $1 = "--help" ]]; then
	usage
    else
	no=`perl -we '($_)=@ARGV; s/^RFC//i; print' "$1"`
	if ! echo "$no"|egrep -q -i '^[0-9]+$'; then
	    usage
	else
	    files=(/usr/share/doc/RFC/links/rfc$no[-.]*)
	    if [ ${#files[*]} -eq 1 ]; then
		# shellcheck disable=SC2128
		#  Expanding an array without an index only gives the first element.
		#  yep, which we confirmed we only have.
		if [ -f "$files" ]; then
		    case "$files" in 
			*.gz)
			    gunzip < "$files" | perl -e '<STDIN>;<STDIN>;while(<STDIN>){print}'|less;;
			*)
			    perl -e '<STDIN>;<STDIN>;while(<STDIN>){print}' < "$files" |less;;
		    esac
		else
		    #http://datatracker.ietf.org/doc/rfc2822/?include_text=1
		    browser "http://datatracker.ietf.org/doc/rfc$no/?include_text=1"
		fi
	    else 
		echo "More than one match:"
		for F in  "${files[@]}" ; do
		    echo "  $F"
		done
	    fi
        fi
    fi
else
    usage
fi

