#!/bin/bash

set -eu

# flags I always use especially on 3G networking. Esp. the --fuzzy.

# needed to prevent triggering my ISP's upload trickling. in kB/sec
bwlimit=${BWLIMIT-50}

if [ -n "$bwlimit" ]; then
    opts="--bwlimit=$bwlimit"
else
    opts=""
fi

set -x

rsync $opts --progress --partial --fuzzy "$@"
