#!/bin/bash

set -eu

# flags I always use especially on 3G networking. Esp. the --fuzzy.

# needed to prevent triggering my ISP's upload trickling.
BWLIMIT=--bwlimit=50

set -x

rsync -avv $BWLIMIT --progress --fuzzy "$@"
