#!/bin/bash

IFS=

logdir=~/log
mkdir -p "$logdir"

did_run=0
onexit() {
    if [ $did_run = 0 ]; then
	did_run=1
	init-xscreensaver start
	init-xwrits-mine start
    fi
}

init-xscreensaver stop
init-xwrits-mine stop

trap onexit EXIT INT

"$@"
