#!/bin/bash

IFS=

logdir=~/log
mkdir -p "$logdir"

daemonize --stop xscreensaver -no-splash
daemonize --stop xwrits-mine

"$@"

daemonize --multilog "$logdir"/xscreensaver --start xscreensaver -no-splash
daemonize --multilog "$logdir"/xwrits --start xwrits-mine

