#!/usr/bin/env perl

my $copyright= <<'COPYRIGHT';
# Copyright 2026 by Christian Jaeger <ch@christianjaeger.ch>
# Published under the same terms as perl itself
COPYRIGHT

use strict;
use utf8;
use warnings;
use warnings FATAL => 'uninitialized';
use experimental 'signatures';

my ($email_full)= $copyright=~ / by ([^\n]*)/s;

my ($mydir, $myname);
BEGIN {
    $0=~ /(.*?)([^\/]+)\z/s or die "?";
    ($mydir, $myname)=($1,$2);
}

#use Chj::ruse;
#use Chj::Backtrace;
#use Chj::xperlfunc ':all';
#use FP::Show; use FP::Repl; use FP::Repl::Trap; #

sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname cmd [ args ]

  Run cmd with args after first changing into the directory of the
  shell running as another child of the parent process (which should
  be an rxvt instance or similar).

  This hack is needed because rxvt runs matcher commands from the dir of the
  rxvt instance, not the shell that is running inside.

  On top of that, removes some parts from the last argument, since I
  can't manage to make the regex work to prioritize some alternative;
  thus remove erroneous parts after the fact. You really do have two
  problems with regexes.

  ($email_full)
";
exit (@_ ? 1 : 0);
}

usage unless @ARGV;

package PidStat {
    # use FP::Struct [
    #     'pid',
    #     'stat_path',
    #     'contents',
    #     ];

    sub get_map($self) {
        my @lines = split /\n/, $self->{contents};
        +{
            map {
                my @key_val = split /:/, $_, 2;
                if (@key_val) {
                    my ($k, $v) = @key_val;
                    $v =~ s/^\s+//s;
                    $v =~ s/\s+\z//s;
                    ($k, $v)
                } else {
                    ()
                }
            } @lines
        }
    }
    
    # _END_
}

my @pidstat =
    map {
        if (m{^/proc/(\d+)/$}) {
            my $stat_path = "${_}status";
            my $contents = do {
                if (open my $in, "<", $stat_path) {
                    local $/;
                    <$in>
                } else {
                    warn "could not open '$stat_path': $!";
                    undef
                }
            };
            bless +{
                pid=> $1,
                stat_path=> $stat_path,
                contents=> $contents
            }, "PidStat"
        } else {
            ()
        }
    } glob "/proc/*/";

my %pidstat_by_pid;
my %pidstat_by_ppid;
for my $ps (@pidstat) {
    $pidstat_by_pid{$ps->{pid}} = $ps;
    my $m = $ps->get_map;
    push @{$pidstat_by_ppid{$m->{PPid}}}, $ps;
}

my $ppid = getppid;
my $parent = $pidstat_by_pid{$ppid}->get_map;

if (not $parent->{Name} =~ /rxvt/) {
    $parent = $pidstat_by_pid{$parent->{PPid}}->get_map;
}

my $children = $pidstat_by_ppid{$parent->{Pid}};

my @bash_children = grep {
    scalar $_->get_map->{Name} =~ /bash/
} @$children;

my @cwd = map {
    my $pid = $_->{pid};
    scalar readlink("/proc/$pid/cwd") or die "readlink: $!"
} @bash_children;

#repl

if (my ($cwd) = @cwd) {
    chdir ($cwd) or die "chdir: $!";

    my ($cmd, @args) = @ARGV;
    if (@args) {
        # Hack up path
        my $s = pop @args;
        if ($s=~ /:\d+:?$/) {
            $s =~ s/^.*? at +//;
        }
        push @args, $s;
    }
    
    exec($cmd, @args) or exit 127
} else {
    die "could not find bash child of rxvt parent(-parent)"
}

