#!/bin/bash

# scratch commit
# for t3 but should also work on novo thanks to the ignores there.

set -eu

usage () {
    echo "$0 [ -m message ]"
    echo " add all, metadata save, commit and push to origin"
    exit 1
}

if [ $# -eq 0 ]; then
    options="-m ."
elif [ $# -eq 2 ]; then
    if [ "$1" = "-m" -o "$1" = "-c" ]; then
	options="$1 $(printf '%q' "$2")"
    else
	usage
    fi
else
    usage
fi


gdir=`git rev-parse --git-dir`
if [ "$gdir" != ".git" ]; then
    echo "not in root of git working directory, aborting"
    exit 1
fi

set -x

git add .

cj-gitmetadata save

# make sure eventual new metadata is added, too:
# need -f because on novo I have * in .gitignore
git add -f .METADATA-v2

if eval "git commit -a $options"; then

    if [ ! -f .git/scoma-no-push ]; then
	git push origin master
    fi

fi
