#!/bin/bash

# scratch commit
# for t3 but should also work on novo thanks to the ignores there.

set -eu

usage () {
    echo "$0 [ -m message | -c commit ] [ -f ]"
    echo "  Add all, run cj-gitmetadata save, commit and push."
    echo "  Note: set up push upstream so that 'git push'"
    echo "  without arguments works."
    echo
    echo "  Options:"
    echo "    -f      run from root of working directory even if not there"
    echo "    -m, -c  passed to git commit"
    exit 1
}

opt_force=0
options=""
seen_m_or_c=0

while [ $# -ne 0 ]; do
    if [[ $1 = "-f" ]]; then
        opt_force=1
        shift
    else
        if [[ $1 = "-m" || "$1" = "-c" ]]; then
	    if [ $# -ge 2 ]; then
                options="$options $1 $(printf '%q' "$2")"
                seen_m_or_c=1
                shift
                shift
            else
                usage
            fi
        else
	    usage
        fi
    fi
done

if [[ $seen_m_or_c = 0 ]]; then
    options="$options -m ."
fi


a=`git rev-parse --show-toplevel`
b=`pwd -P`
if [ "$a" != "$b" ]; then
    if [[ $opt_force = 1 ]]; then
        cd "$a"
    else
        a=$(chase "$a")
        b=$(chase "$b")
        if [ "$a" != "$b" ]; then
	    echo "not in root of git working directory and -f not given, aborting"
	    exit 1
        fi
    fi
fi

if [ ! -d .METADATA-v2 ]; then
    echo "scoma is being run for the first time in this repository,"
    echo "there is no .METADATA-v2 directory yet. Are you sure you"
    echo -n "want to start recording metadata? [y/n] "
    read ans
    if [ "$ans" = y -o "$ans" = yes -o "$ans" = Yes -o "$ans" = Y ]; then
        true
    else
        echo "Cancelled by user request."
        exit 2
    fi
fi


set -x

git add .

if [ -f .git/scoma-no-user-group ]; then
    cj-gitmetadata save --no-user-group
else
    cj-gitmetadata save
fi

# make sure eventual new metadata is added, too:
# need -f because on novo I have * in .gitignore
git add -f .METADATA-v2

if eval "git commit -a $options"; then

    if [ ! -f .git/scoma-no-push ]; then
	git push
    fi

fi
