#!/bin/bash

set -eu

if [ $# -ne 1 ]; then
	echo "usage: $0 dir"
	cat <<'EOF'
 clean up issues in SVN or similar checkouts, so that the tree can be
 'cleanly' diffed against another one from a tarball, for example.
 NOTE: currently acts on ALL files, even binaries
	exit 1
fi

dir="$1"

find -type f | myxargs recode_lf -B

mysed 's/\$(Revision|Author|Date|Id):.*?\$/\$$1\$/g' -r "$dir" .

