#!/bin/bash

set -eux


if git status |grep '^nothing to commit' -q; then

    git pull || true

    cj-gitmetadata restore

else

    cat <<EOF
There are changes in the local directory. Aborting.
EOF

fi
