#!/bin/bash

set -eux


if git status |grep '^nothing to commit' -q; then

    git pull || true

    if [ -f .git/scoma-no-user-group ]; then
	cj-gitmetadata restore --no-user-group
    else
	cj-gitmetadata restore
    fi

else

    cat <<EOF
There are changes in the local directory. Aborting.
EOF

fi
