#!/usr/bin/perl -w

# Mit Jun  7 18:25:14 CEST 2006
(my $email='pflanze%gmx,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?"; 
my ($mydir, $myname)=($1,$2); 
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname number

  Shows that srfi using links.

  Options:
  --top|--parent|--overview  show the overview page instead

  (Christian Jaeger <$email>)
";
exit @_ ? 1 : 0;
}

my @args;
my $DEBUG=0;
my $opt_overview;

for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
    } elsif (/^--?(o(verview)?|t(op)?|p(arent)?)$/) {
	$opt_overview=1;
#     } elsif (/^--?X(?:XXX(?:=(.*))?)?$/) {
#         if (defined $1) {
#             $XXX=$1
#         } else {
#             $XXX=$ARGV[++$i] or usage "missing argument for '$_' option";
#         }
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}
usage unless @args==1;

my ($num)=@args;
$num=~ /^\d+\z/ or usage "not a number: '$num'";

#use Chj::Web::Fetch 'get_remote_file_ref';
#use Chj::xtmpfile;
use Chj::xperlfunc;

#for my $base (qw(

# my $t= xtmpfile;
# $t->xprint($$c);
# $t->xclose;

# xxsystem "links",$t->path;


# final:
# http://srfi.schemers.org/srfi-0/
# http://srfi.schemers.org/srfi-0/srfi-0.html

# draft:
# http://srfi.schemers.org/srfi-64/
# http://srfi.schemers.org/srfi-64/srfi-64.html

# withdrawn:
# http://srfi.schemers.org/srfi-73/
# http://srfi.schemers.org/srfi-73/srfi-73.html

# I'm superduper. Now I've begun writing a perl thing  etc  cause I thought they could have differnt locations  now that's notthecase.



xexec "links",
  ($opt_overview ?
   "http://srfi.schemers.org/srfi-$num/"
   : "http://srfi.schemers.org/srfi-$num/srfi-$num.html");


