#!/bin/bash

set -x
ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key.pub
ssh-keygen -l -f /etc/ssh/ssh_host_dsa_key.pub
#ssh-keygen -l -f /etc/ssh/ssh_host_key
ssh-keygen -l -f /etc/ssh/ssh_host_ecdsa_key.pub


set +x

# https://superuser.com/questions/929566/sha256-ssh-fingerprint-given-by-the-client-but-only-md5-fingerprint-known-for-se

# helper functions
tablize () { 
    awk '{printf("| %-7s | %-7s | %-47s |\n", $1, $2, $3)}'
}

LINE="+---------+---------+-------------------------------------------------+"

# header
echo $LINE
echo "Cipher" "Algo" "Fingerprint" | tablize
echo $LINE

# fingerprints
for host_key in /etc/ssh/ssh_host_*_key.pub
do
    if [[ -f "$host_key" ]]; then
	cipher=$(echo "$host_key" | sed -r 's/^.*ssh_host_([^_]+)_key\.pub$/\1/' | tr '[a-z]' '[A-Z]')
	md5=$(ssh-keygen -E md5 -l -f "$host_key" | awk '{print $2}' | sed 's/MD5://')
	sha256=$(ssh-keygen -E sha256 -l -f "$host_key" | awk '{print $2}' | sed 's/SHA256://')
	echo "$cipher" MD5 "$md5" | tablize
	echo "$cipher" SHA-256 "$sha256" | tablize
	echo $LINE
    else
	# echo "$0 ???: $host_key" -- "HostKey"
	true
    fi
done


echo "That's all."
