#!/usr/bin/perl -w

# Mon Dez 23 17:11:53 CET 2002

use strict;

$0=~ /([^\/]+)$/s or die "?";
my $myname=$1;
sub usage {
    print "$myname [ strace_options ] command

  Show the file arguments of successful open and optionally other file
  related calls.

  Options:
  -a|--all  show the arguments of all file related calls, not just open
            calls
  -o outputfile
            (default: print to stderr)
  -T        don't trim (by default only output the filename, not the
            whole strace line)
";
exit @_;
}


my (@options,@files);
my $opt_output;
my $opt_trim=1;
my $opt_all;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @files, @ARGV[$i+1..$#ARGV];
	# XX should '--' into argument list, but see below
    	last;
    } elsif ($_ eq '-o') {
        $opt_output= $ARGV[++$i] || usage;
    } elsif (/^--?a(ll)?$/) {
        $opt_all=1;
    } elsif (/^--?t(rim)?$/) {
        $opt_trim=1;
    } elsif (/^--?T(rim)?$/) {
        $opt_trim=0;
    } elsif (/^-/) {
        push @options,$_
    } else {
    	#push @files, $_
        push @files, @ARGV[$i..$#ARGV];
	# XX see above
	last;
    }
}
usage unless @files;

my $traceclass= $opt_all ? "file" : "open";
my @traceoptions= ("-e","trace=$traceclass");

if ($opt_output) {
    unless ($opt_output=~ /^[<>|]/) {
	$opt_output= ">$opt_output";
	exec "strace",@options,@traceoptions,
	  "-o",
	    $opt_trim ?
	      "| perl -e 'open STDOUT,\"$opt_output\" or die \$!; \$|=1; while(<STDIN>){print \"\$1\\n\" if /\"(.*?)\", .*\\d\$/}'"
	      : "| perl -e 'open STDOUT,\"$opt_output\" or die \$!; \$|=1; while(<STDIN>){print if /\\d\$/}'",
	    @files;
    }
} else {
    exec "strace",@options,@traceoptions,
      "-o",
	$opt_trim ?
	  "| perl -ne 'print STDERR \"\$1\\n\" if /\"(.*?)\", .*\\d\$/'"
	  : "| perl -ne 'print STDERR \$_ if /\\d\$/'",
	@files;
}
