#!/usr/bin/perl -w

# Mon Sep 30 21:22:11 BST 2013
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname ..

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
#our $opt_dry;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   #"dry-run"=> \$opt_dry,
	   ) or exit 1;
#usage unless @ARGV;

# from scratch because straceopens didn't work anymore, something.

while (<>) {
    if (my ($path)= m/^(?:\d+\ )?
		      open\(\"(.*?)\",/x) {
	$path=~ s/\\"/"/sg;
	# other stuff?
	print $path, "\n"
    }
}


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
