#!/bin/bash

usage () {
    echo "usage: $0 user"
    echo " Same(?) as suxterm from the sux package but starts 'term'."
    exit 1
}

if [ $# -eq 1 ]; then
    if [ "$1" = "-h" -o "$1" = "--help" ]; then
	usage
    else
	sux - "$1" term
    fi
else
    usage
fi

