#!/bin/bash

set -eu

usage () {
    echo "usage: $0 [-] user-or-homedir [ term-arguments... ]"
    echo " Same(?) as suxterm from the sux package but starts 'term'."
    echo " Also, user-or-homedir is mapped to the user using user-or-home2user."
    echo " The optional '-' argument is ignored (this is just to make "
    echo " changing a command line from 'sux - user' easier)."
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

if [ "$1" = "-" ]; then
    shift
fi

if [ $# -lt 1 ]; then
    usage
fi

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
    usage
fi

user=$(user-or-home2user "$1")
shift

sux - "$user" term "$@"

