#!/bin/bash

set -e

if [ -n "$TAB_EXPAND_N" ]; then 
    N=$TAB_EXPAND_N  # w/o quotes so code can be given ok?
else
    N=4
fi

if [ $# -gt 0 ]; then
    for file in "$@"; do
	tmp="$(tempfile -d "$(dirname "$file")")"
	expand --tabs=$N < "$file" > "$tmp"  ## no quotes around $N?
	PERMS="`perms-of "$file"`"
	mvnumber -a "_vor_tab-expand" "$file"
	mv -i "$tmp" "$file" # should rather throw an error immediately.
	chmod "$PERMS" "$file"
    done
else
    echo "usage: $0 file(s)"
    echo "  expands file(s)'s tabs to spaces using tabstops $N,"
    echo "  keeping old version using mvnumber."
    echo "  tabstops can be overridden by the env var TAB_EXPAND_N."
fi


