#!/usr/bin/perl -w

# Tue May 27 22:45:05 CEST 2008
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

use POSIX qw(setsid);

my $pid=fork;
defined
  $pid or die "fork: $!";
if ($pid) {
    exit 0;#well. bugg.buti dontcarenow
} else {
    setsid or die $!;

    # setting to xterm seems to work? whereas without it
    #  (older) debian (without urxvt installed) usually gives
    # "Cannot find terminfo entry for 'rxvt-unicode'"
    my $run= sub {
	my (@args)=@_;
	exec "urxvt", ("-tn", "xterm",
		       ($> == 0 ? ("-bg", "#ffd8d8") : ()),
		       @args)
	  or exit 127;
    };
    if (@ARGV==1
	# and stat $ARGV[0]
	#and  regex? but relative paths. no way.
	#just make sure options won't do wrong:
	and not $ARGV[0]=~ /^-/
       ) {
	chdir $ARGV[0]
	  or die "could not chdir '$ARGV[0]': $!";
	&$run();
    } else {
	&$run(@ARGV)
    }
}


