#!/usr/bin/perl -w

# Sat Aug 27 20:56:49 EDT 2011
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict; use warnings FATAL => 'uninitialized';
use utf8;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname value[s]

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

usage unless @ARGV;
my $first=$ARGV[0];
usage if $first eq "-h" or $first eq "--help";

utf8::decode($myname);

our $conv=
  +{
    "°C"=> sub {
	my ($v)=@_;
	(($v*9/5)+32)." °F"
    },
    "°F"=> sub {
	my ($v)=@_;
	(($v - 32)*5/9)." °C"
    },
    "feet"=> sub {
	my ($v)=@_;
	($v * 0.3048)." m, ".($v * 12). " in"
    },
    do {
	my $f= sub {
	    my ($gal)=@_;
	    my $imperial_gallon= 4.54609; # l, used in the United
                                          # Kingdom, Canada, and some
                                          # Caribbean nations
	    my $US_gallon= 3.785; # l, used in the US and some Latin
                                  # American and Caribbean countries

	    # While there is no official symbol for the gallon (as
	    # there are for SI units), gal is in common use.
	    "$gal gal (imperial) = ".($gal * $imperial_gallon)." l"
	      .", $gal gal (US) = ".($gal * $US_gallon)." l"
	};
	(gal=> $f,
	 gallon=> $f)
    },
   }->{$myname}
  or die "unknown name '$myname'";

print &$conv ($_)."\n"
    or die $!
    for @ARGV;


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
