#!/usr/bin/perl -w

# Mon Dec 16 16:27:16 GMT 2013
(my $email='ch%christianjaeger,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname ..

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

use Getopt::Long;
our $verbose=0;
#our $opt_dry;
GetOptions("verbose"=> \$verbose,
	   "help"=> sub{usage},
	   #"dry-run"=> \$opt_dry,
	   ) or exit 1;
usage unless @ARGV;

while (<>) {
    chomp;
    if (length) {
	print;
	print " " unless / $/;
    } else {
	print "\n\n";
    }
}
print "\n";

#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
