#!/usr/bin/perl -w

# Fre Aug 10 20:46:00 CEST 2007
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname ..

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

my @args;
my $DEBUG=0;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}


use URI;
use Encode;

sub url_decode {
    my ($str)=@_;
    $str=~ s/([\r\n]*)\z//s;
    my $eol= $1;
    local our $u= URI->new($str);
    local our $str2= $u->uri_unescape;
    decode("utf-8", $str2, Encode::FB_CROAK).$eol
}

#our $foo= url_decode 'induktivit%C3%A4ten+s%C3%A4ttigung';
#use Chj::repl;repl;

while (<>) {
    print (url_decode $_) or die "printing to stdout: $!"
}

