#!/usr/bin/perl -w

# Fre Sep  7 11:43:44 CEST 2007
(my $email='pflanze%gmx,ch')=~ tr/%,/@./;

use strict;

our $sleeptime= 0.3;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname cmd file(s)

  watch given file(s) for changes, if a change happens, run cmd (which is
  run using perl's system call thus can contain shell stuff).


  Options:
   -a  also run before waiting

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

my @args;
my $DEBUG=0;
our $verbose;
our $opt_a;
for (my $i=0; $i<=$#ARGV; $i++) {
    local $_=$ARGV[$i];
    if (/^--?h(elp)?$/) {
    	usage
    } elsif ($_ eq '--') {
    	push @args, @ARGV[$i+1..$#ARGV];
    	last;
    } elsif (/^--?d(ebug)?$/) {
	$DEBUG=1;
    } elsif (/^--?a$/) {
	$opt_a=1;
    } elsif (/^--?v(erbose)?$/) {
	$verbose=1;
#     } elsif (/^--?X(?:XXX(?:=(.*))?)?$/) {
#         if (defined $1) {
#             $XXX=$1
#         } else {
#             $XXX=$ARGV[++$i] or usage "missing argument for '$_' option";
#         }
    } elsif (/^-./) {
    	usage("Unknown option '$_'\n");
    } else {
    	push @args, $_
    }
}
usage unless @args>1;

use Time::HiRes 'sleep';
use Chj::xperlfunc;# 'xstat';
use Chj::Unix::exitcode;

our $cmd=shift @args;
our @files= @args;

our @stats= map { scalar xstat $_ } @files; #vergiss das scalar nicht ach isch prl shit.

xxsystem $cmd
  if $opt_a;

while (1) {
    sleep $sleeptime;
  CHECK: {
	for (my $i=0; $i<@files; $i++) {
	    local our $s= xstat $files[$i];
	    # hm wieder mal stat vergleich hm  gibts da  was dort schon von mir ?
	    #use Chj::repl;repl;
	    #nein.~sgh. ok now.
	    if ($s->equal ($stats[$i])) {
		# no change
		#print "'$files[$i]' has not changed\n" if $DEBUG;
	    } else {
		print "--- ".localtime().": '$files[$i]' has changed -------------\n" if $verbose;
		$stats[$i]=$s;
		my $rv= xsystem $cmd;
		if ($rv==0) {
		    last CHECK;
		} else {
		    die "command exited with ".exitcode($rv);
		}
	    }
	}
    }
}
