#!/usr/bin/perl -w

my $name="whereami";
use strict;

my $file= "/var/lib/whereami";

sub usage {
    print "usage:
  $0 prefix
    -or-
  $0 -s locationname

 Print current location name, prefixed with \$prefix-.
 Or save new location name (to '$file'), and do some other
 changes to adapt to it.
";
    exit;
}

sub switchto {
    my $where=shift;
    my $rv= system "cp","-f","/etc/resolv.conf.$where", "/etc/resolv.conf.TMP";
    if ($rv!=0){
	die "cp returned error status $rv";
    }
    rename "/etc/resolv.conf.TMP","/etc/resolv.conf"
      or warn "Could not re-link resolv.conf: $!";
}

sub get {
    open IN, "<$file" or exit(1);
    my $setting= <IN>; chomp $setting;
    close IN;
    $setting
}

sub printit ( $ ) {
    my ($prefix)=@_;
    print $prefix."-".get."\n"
      or die $!;
}


sub rulez {
    my $where=shift;
    defined $where and length $where or return;
    if ($where=~ m|^/etc/resolv.conf.([^/]+)\z|) {
	return $1;
    } elsif (not $where=~ m|/|) {
	$where
    } else {
	undef
    }
}

sub setitto {
    my $whereorig=shift;
    if (my $where= rulez $whereorig) {
	my $old;
	if (open IN, "<$file") {
	    $old= <IN>;
	    chomp $old;
	    close IN;
	}
	# switch anyway, even if $old is same as new. Since
	# inserting wireless card changes the resolv.conf without
	# changing the whereami status file!
	switchto($where);
	open OUT, ">$file" or die "$name: Could not write to $file: $!\n";
	print OUT $where."\n";
	close OUT;
    } else {
	warn "$name: parameter `$whereorig' doesn't conform to rules. Ignoring.\n";
    }
}

if (@ARGV==1) {
    if ($ARGV[0]=~ /^--?h/) {
	usage
    } else {
	printit($ARGV[0])
    }
} elsif (@ARGV==2 and $ARGV[0] eq '-s') {
    setitto($ARGV[1]);
    printit ($ARGV[1]);
} else {
    usage
}

