#!/bin/bash

set -eu

if [ $# -lt 2 ]; then
	echo "usage: $0 outfile program arguments"
	echo "  runs program with arguments and outputs gdb log to"
	echo "  \${outfile}.log and the backtrace to \${outfile}_backtrace.txt"
	exit 1
fi

outfile="$1"
shift
program="$1"
shift

cmdfile=`tempfile`
logfile="${outfile}.log"
backtracefile="${outfile}_backtrace.txt"

moveold () {
    if test -e "$1"; then
	mvnumber "$1" || true
    fi
}

moveold "$logfile"
moveold "$backtracefile"

##todo: can't use quotes in cmd files. but what about files with spaces?...
##[todo: how to do if / else around the run command to only do "bt full" if it segfaulted?]
cat <<EOF > "$cmdfile"
set pagination off
set logging file $logfile
set logging on
set logging redirect on
run
set logging off
set logging redirect off
set logging file $backtracefile
set logging on
set logging redirect on
bt full
quit
EOF

gdb -x "$cmdfile" -batch-silent --args "$program" "$@"
rm "$cmdfile"

if [ "No stack." == "`cat "$backtracefile"`" ]; then
    rm "$backtracefile"
fi

# produce a success/error exit code:
tail -1 "$logfile" | grep --quiet "Program exited normally"
