#!/bin/bash

set -euo pipefail
IFS=

myname=$(basename "$0")

lastfile_or_lastdir=${myname//with-/}

usage () {
    echo "with-${lastfile_or_lastdir} proc [args]"
    echo "  call \`with-${lastfile_or_lastdir}-in . proc [ args ]\`."
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

exec with-${lastfile_or_lastdir}-in . "$@"
