#!/bin/bash

set -euo pipefail
IFS=


myname=$(basename "$0")

lastfile_or_lastdir=${myname//with-/}
lastfile_or_lastdir=${lastfile_or_lastdir//-in/}

usage () {
    echo "with-lastfile-in dirpath proc [args]"
    echo "with-lastdir-in dirpath proc [args]"
    echo "  Call proc with args and \`${lastfile_or_lastdir} --fullpath \$dirpath\` as "
    echo "  additional last argument."
    echo "  Also see: xlastfile, with-lastfile"
    exit 1
}

if [ $# -lt 2 ]; then
    usage
fi

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

dirpath="$1"
shift

dirpath2=$("${lastfile_or_lastdir}" --fullpath "$dirpath")

exec "$@" "$dirpath2"
