#!/bin/sh

df_colorize () {
    perl -wne '
         our $ESC; BEGIN { $ESC= chr(27) }
         s{(\s)(\d+)(%[^\n]*)}{
                my ($w,$percent,$rest)= ($1,$2,$3);
                if ($percent >= 95) {
                      $w.$ESC."[31m".$percent.$rest.$ESC."[0m"
                } else {
                      $w.$percent.$rest
                }
         }e;
         print or die
    '
}


uptime

echo

who | printfield 1 | csort | uniq -c

echo

free

echo

df | gr -v '^(/dev/loop|udev|tmpfs)' | df_colorize

echo

df | gr '^(udev|tmpfs)' | df_colorize

