#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "xlastfile proc [dirpaths]"
    echo "  Call proc with dirpaths passed through \`lastfile --fullpath\`."
    echo "  Without dirpaths, call proc with \`lastfile --fullpath .\`."
    echo "  Also see: with-lastfile"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

proc="$1"
shift

lf () {
    local dir="$1"
    lastfile --fullpath "$dir"
}

if [ $# = 0 ]; then
    exec "$proc" "$(lf .)"
else
    declare -A a
    a=()

    for d in "$@"; do
	a[${#a[@]}]="$(lf "$d")"
    done

    exec "$proc" "${a[@]}"
fi

