#!/bin/bash

# Depends: (lastfile lastdir)

set -euo pipefail
IFS=

myname=$(basename "$0")

lastfile_or_lastdir=${myname//x/}

usage () {
    echo "xlastfile proc [dirpaths]"
    echo "xlastdir proc [dirpaths]"
    echo "  Call proc with dirpaths passed through \`$lastfile_or_lastdir --fullpath\`."
    echo "  Without dirpaths, call proc with \`$lastfile_or_lastdir --fullpath .\`."
    echo "  Also see: with-lastfile"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

proc="$1"
shift

lf () {
    local dir="$1"
    "$lastfile_or_lastdir" --fullpath "$dir"
}

if [ $# = 0 ]; then
    exec "$proc" "$(lf .)"
else
    declare -A a
    a=()

    for d in "$@"; do
	a[${#a[@]}]="$(lf "$d")"
    done

    exec "$proc" "${a[@]}"
fi

