#!/usr/bin/perl -w

# Verwendet xscreensaver als xlock

system "nice nice xscreensaver &";
#sleep 3; # 1 scheint zuwenig (Sat,  4 May 2002 01:30:55 +0200), shit es gibt keinen weg rauszufinden ob er bereit ist?
	# Ah, kann einfach xscreensaver-command: no screensaver is running on display :0.0 testen unten

# forkoffwatch:
pipe READ,WRITE;
my $chpid=fork();
defined $chpid or die "Could not fork: $!";
if ($chpid) {
	close WRITE;
} else {
	close READ;
	open STDOUT, ">&WRITE" or die "Could not dup: $!";
	# NO sleep here, must see the 'LOCK'
	exec qw/xscreensaver-command -watch/;
}

sleep 1; # let watcher finish startup

do {system "xscreensaver-command -lock"} until $?==0;

while (<READ>) {
	if (/^LOCK/) { $maykill=1; next };
	if (/^UNBLANK/ and $maykill) {
		# finished now.
		system "xscreensaver-command -exit";
		kill 3, $chpid or die "Could not terminate child: $!";
		print "OK!\n";
		exit;
	}
}

