#!/bin/bash

set -euo pipefail
IFS=

usage () {
    {
	echo "$0 [file]"
	echo "  Without argument, reads from stdin. "
	echo "  Calls xml-to-sexpr but also pretty-prints via Gambit."
    } >&2
    exit 1
}

if [ $# -gt 1 ]; then
    usage
fi

if [ $# -eq 1 ]; then
    if [ "$1" = "-h" -o "$1" = "--help" ]; then
	usage
    fi
fi

xml-to-sexpr "$@" | { cd / && gsi -e '(pretty-print (read))' ; }

