#!/usr/bin/perl -w

# Sat Aug 27 20:56:49 EDT 2011
(my $email='XXX%YYY,ch')=~ tr/%,/@./;

use strict;
use utf8;

$0=~ /(.*?)([^\/]+)\z/s or die "?";
my ($mydir, $myname)=($1,$2);
sub usage {
    print STDERR map{"$_\n"} @_ if @_;
    print "$myname value[s]

  (Christian Jaeger <$email>)
";
exit (@_ ? 1 : 0);
}

usage unless @ARGV;
my $first=$ARGV[0];
usage if $first eq "-h" or $first eq "--help";

utf8::decode($myname);

our $conv=
  +{
    "°C"=> sub {
	my ($v)=@_;
	#use fatal warnings somethng ?
	["°F", ($v*9/5)+32]
    },
    "°F"=> sub {
	my ($v)=@_;
	["°C", ($v - 32)*5/9]
    },
    "feet"=> sub {
	my ($v)=@_;
	["m", $v * 0.3048 ]
    }
   }->{$myname}
  or die "unknown name '$myname'";

sub print_conv {
    my ($U,$v)=@{ &$conv ($_[0])};
    print "$v $U\n"
      or die $!;
}

print_conv $_ for @ARGV;


#use Chj::ruse;
#use Chj::Backtrace; use Chj::repl; repl;
